/**
 * 写作模式客户端文案（zh / en）与选择器。
 * 纯数据 + 纯函数；不依赖 React / DOM 事件 / Harness。
 */
const zh = {
  toggle: '写作模式',
  exit: '退出写作',
  docs: '文档库',
  newProject: '新建项目',
  projTitle: '项目名',
  projPremise: '一句话前提',
  projTemplate: '模板',
  create: '创建',
  cancel: '取消',
  created: '已创建项目',
  untitled: '未命名',
  save: '保存',
  saved: '已保存',
  saving: '保存中…',
  ai: '写作伙伴',
  polish: '润色',
  continue: '续写',
  outline: '大纲',
  compress: '压缩',
  expand: '扩写',
  research: '找资料',
  spark: '灵感',
  insert: '插入文末',
  replaceSel: '替换选区',
  sendChat: '发送到会话',
  toolsMenu: '文字工具',
  toolsArmedHint: '可补充要求，Enter 运行 · Esc 取消',
  toolTitlePolish: '保持原意，提升可读性与节奏',
  toolTitleContinue: '顺着现有风格往下写一段',
  toolTitleOutline: '为这段文字生成简洁大纲',
  toolTitleCompress: '压到约一半长度，保留要点',
  toolTitleExpand: '补足论证与例子，篇幅约翻倍',
  toolTitleResearch: '围绕这段文字联网查公开资料',
  toolTitleSpark: '来几个可以写的新点子',
  applying: '处理中…',
  noText: '先选中或写点内容',
  aiUnavailable: '未连接模型服务。可先「发送到会话」，由主对话处理。',
  empty: '还没有库根。点 + 选择写作文件夹（例如 E:\\剧本）。',
  emptyCta: '一键加入 E:\\剧本',
  noProjects: '该库下没有含 project.md 的项目。可打开任意 .md / .fountain。',
  focus: '专注',
  archive: '档案',
  archiveHint: '作品档案：设定、进度与资料的 wiki 站（随当前文稿所属作品）',
  archiveNeedDoc: '先打开一篇稿件：作品档案跟着「当前文稿所属的作品」走；一个作品都没有时，先在库面板里新建或添加作品。',
  noChapters: '还没有章节',
  firstChapter: '写第一章',
  newChapter: '新章节',
  chars: '字',
  openAi: 'AI',
  closeAi: '收 AI',
  gates: '成稿检查',
  gateShort: '检查',
  runGates: '检查一遍',
  gatesPass: '全部通过',
  gatesFail: '{n} 项未达标',
  gatesNone: '不支持该类型',
  gatesIdle: '打开一篇文稿后可运行检查。',
  saveAsNew: '另存为新版',
  bumpHint: '按文件名生成 v(N+1)，保留旧稿',
  hideLib: '收起库',
  showLib: '展开库',
  search: '搜索文件…',
  openLatest: '打开最新版',
  isHistory: '历史稿',
  isLatest: '当前版',
  versions: '版本',
  comparePrev: '对比上一版',
  closeDiff: '关闭对比',
  diffTitle: '与上一版对比',
  reviewFix: '按此评审改稿',
  ledger: '伏笔与线索',
  ledgerHook: '当前钩子',
  ledgerFores: '伏笔未兑现',
  ledgerReview: '最新评审',
  ledgerTimeline: '时间线尾条',
  ledgerNone: '打开项目内文件后显示',
  addRoot: '添加库…',
  switchRoot: '切换库',
  missing: '路径失效',
  unsaved: '未保存',
  copyPath: '复制路径',
  copied: '已复制',
  stats: '码字',
  statsToday: '今日净增',
  statsStreak: '连续',
  statsStreakUnit: '天',
  statsGoal: '日更目标',
  statsGoalUnit: '字',
  statsGoalSave: '保存目标',
  statsGoalSaved: '目标已保存',
  statsNone: '打开项目内文件后统计今日码字',
  statsNoData: '保存后开始累计',
  findPlaceholder: '查找…',
  replacePlaceholder: '替换为…',
  findPrev: '上一个',
  findNext: '下一个',
  findReplace: '替换',
  findReplaceAll: '全部替换',
  findClose: '关闭查找',
  findNone: '无结果',
  findHint: 'Enter 下一个 · Shift+Enter 上一个',
  hemingway: '海明威',
  hemingwayHint: '海明威模式：禁用退格/删除/剪切，只往前写（初稿防回改）',
  typewriter: '打字机',
  typewriterHint: '打字机滚动：输入时把光标所在行保持在一屏中部',
  rewriteTitle: '改稿预览',
  rewriteAccept: '采纳改稿',
  rewriteDiscard: '丢弃',
  rewriteApplied: '改稿已采纳，可用 Ctrl+Z 撤销',
  rewriteLost: '原选区已变化且无法定位，请重新选区生成',
  emptyTitle: '一张空页。',
  emptyNew: '新建一篇',
  emptyBrowse: '从库里打开',
}
const en = {
  toggle: 'Writing',
  exit: 'Exit writing',
  docs: 'Library',
  newProject: 'New project',
  projTitle: 'Title',
  projPremise: 'Premise',
  projTemplate: 'Template',
  create: 'Create',
  cancel: 'Cancel',
  created: 'Project created',
  untitled: 'Untitled',
  save: 'Save',
  saved: 'Saved',
  saving: 'Saving…',
  ai: 'Assistant',
  polish: 'Polish',
  continue: 'Continue',
  outline: 'Outline',
  compress: 'Compress',
  expand: 'Expand',
  research: 'Research',
  spark: 'Sparks',
  insert: 'Append',
  replaceSel: 'Replace selection',
  sendChat: 'Send to chat',
  toolsMenu: 'Writing tools',
  toolsArmedHint: 'Add a note, Enter to run · Esc to cancel',
  toolTitlePolish: 'Keep meaning, improve readability and rhythm',
  toolTitleContinue: 'Continue in the same style',
  toolTitleOutline: 'Make a compact outline of this text',
  toolTitleCompress: 'Compress to about half, keep the key points',
  toolTitleExpand: 'Add arguments and examples, roughly double the length',
  toolTitleResearch: 'Search public sources about this text',
  toolTitleSpark: 'A few fresh ideas to write about',
  applying: 'Working…',
  noText: 'Select or write something first',
  aiUnavailable: 'No model service. Use Send to chat for now.',
  empty: 'No library root. Click + to pick a folder (e.g. E:\\剧本).',
  emptyCta: 'Add E:\\剧本',
  noProjects: 'No project.md under this root. You can still open any .md / .fountain.',
  focus: 'Focus',
  archive: 'Wiki',
  archiveHint: 'Project wiki: settings, progress and materials (follows the project of the open document)',
  archiveNeedDoc: 'Open a document first — the wiki follows the project of the open document. If you have no project yet, create or add one in the library pane.',
  noChapters: 'No chapters yet',
  firstChapter: 'Start chapter one',
  newChapter: 'New chapter',
  chars: 'chars',
  openAi: 'AI',
  closeAi: 'Hide AI',
  gates: 'Checks',
  gateShort: 'Check',
  runGates: 'Run checks',
  gatesPass: 'All pass',
  gatesFail: '{n} failed',
  gatesNone: 'Unsupported type',
  gatesIdle: 'Open a document to run checks.',
  saveAsNew: 'Save as v+1',
  bumpHint: 'Create -v(N+1) keeping the old draft',
  hideLib: 'Hide library',
  showLib: 'Show library',
  search: 'Search files…',
  openLatest: 'Open latest',
  isHistory: 'History',
  isLatest: 'Current',
  versions: 'Versions',
  comparePrev: 'Diff vs prev',
  closeDiff: 'Close diff',
  diffTitle: 'Diff vs previous',
  reviewFix: 'Fix from review',
  ledger: 'Threads',
  ledgerHook: 'Chapter hook',
  ledgerFores: 'Open foreshadows',
  ledgerReview: 'Latest review',
  ledgerTimeline: 'Timeline tail',
  ledgerNone: 'Open a project file',
  addRoot: 'Add library…',
  switchRoot: 'Library',
  missing: 'Missing',
  unsaved: 'Unsaved',
  copyPath: 'Copy path',
  stats: 'Stats',
  statsToday: 'Today',
  statsStreak: 'Streak',
  statsStreakUnit: 'd',
  statsGoal: 'Daily goal',
  statsGoalUnit: 'chars',
  statsGoalSave: 'Save goal',
  statsGoalSaved: 'Goal saved',
  statsNone: 'Open a file inside a project to track daily writing',
  statsNoData: 'Starts counting on save',
  findPlaceholder: 'Find…',
  replacePlaceholder: 'Replace with…',
  findPrev: 'Previous',
  findNext: 'Next',
  findReplace: 'Replace',
  findReplaceAll: 'Replace all',
  findClose: 'Close find',
  findNone: 'No matches',
  findHint: 'Enter next · Shift+Enter previous',
  hemingway: 'Hemingway',
  hemingwayHint: 'Hemingway mode: disable backspace/delete/cut — keep writing forward',
  typewriter: 'Typewriter',
  typewriterHint: 'Typewriter scrolling: keep the caret line around mid-screen while typing',
  rewriteTitle: 'Rewrite preview',
  rewriteAccept: 'Accept',
  rewriteDiscard: 'Discard',
  rewriteApplied: 'Rewrite applied — Ctrl+Z to undo',
  rewriteLost: 'The original selection moved and cannot be located; select and generate again',
  copied: 'Copied',
  emptyTitle: 'A blank page.',
  emptyNew: 'Start a new piece',
  emptyBrowse: 'Open from library',
}


export function pickLocale() {
  try {
    const lang = String(navigator.language || '').toLowerCase()
    return lang.startsWith('zh') ? zh : en
  } catch {
    return zh
  }
}

export const T = pickLocale()
export { zh, en }
