/**
 * 写作模式客户端文案（zh / en）与选择器。
 * 纯数据 + 纯函数；不依赖 React / DOM 事件 / Harness。
 */
const zh = {
  toggle: '写作模式',
  exit: '退出写作',
  docs: '文档库',
  newDoc: '新建',
  newProject: '新建项目',
  projTitle: '项目名',
  projPremise: '一句话前提',
  projTemplate: '模板',
  create: '创建',
  cancel: '取消',
  created: '已创建项目',
  untitled: '未命名',
  save: '保存',
  saved: '已保存',
  saving: '保存中…',
  delete: '删除',
  confirmDelete: '删除这篇文档？',
  ai: '写作伙伴',
  polish: '润色',
  continue: '续写',
  outline: '大纲',
  compress: '压缩',
  expand: '扩写',
  research: '找资料',
  spark: '灵感',
  insert: '插入文末',
  replaceSel: '替换选区',
  sendChat: '发送到会话',
  applying: '处理中…',
  noText: '先选中或写点内容',
  aiUnavailable: '内核未提供 LLM 服务，可「发送到会话」由主对话完成。',
  empty: '还没有库根。点 + 选择写作文件夹（例如 E:\\剧本）。',
  emptyCta: '一键加入 E:\\剧本',
  noProjects: '该库下没有含 project.md 的项目。可打开任意 .md / .fountain。',
  focus: '专注',
  chars: '字',
  words: '字数',
  openAi: 'AI',
  closeAi: '收 AI',
  gates: '门禁',
  gateShort: '门禁',
  runGates: '跑门禁',
  gatesPass: '全部通过',
  gatesFail: '{n} 项未达标',
  gatesNone: '不支持该类型',
  gatesIdle: '打开 .md / .fountain 后可跑门禁',
  saveAsNew: '另存为新版',
  bumpHint: '按文件名生成 v(N+1)，保留旧稿',
  hideLib: '收起库',
  showLib: '展开库',
  search: '搜索文件…',
  openLatest: '打开最新版',
  isHistory: '历史稿',
  isLatest: '当前版',
  versions: '版本',
  comparePrev: '对比上一版',
  closeDiff: '关闭对比',
  diffTitle: '与上一版对比',
  reviewFix: '按此评审改稿',
  ledger: '台账速览',
  ledgerHook: '当前钩子',
  ledgerFores: '伏笔未兑现',
  ledgerReview: '最新评审',
  ledgerTimeline: '时间线尾条',
  ledgerNone: '打开项目内文件后显示',
  addRoot: '添加库…',
  switchRoot: '切换库',
  removeRoot: '移除',
  missing: '路径失效',
  unsaved: '未保存',
  pathLabel: '路径',
  suggestRoot: '建议加入库：',
  addSuggest: '加入库',
  copyPath: '复制路径',
  copied: '已复制',
}
const en = {
  toggle: 'Writing',
  exit: 'Exit writing',
  docs: 'Library',
  newDoc: 'New',
  newProject: 'New project',
  projTitle: 'Title',
  projPremise: 'Premise',
  projTemplate: 'Template',
  create: 'Create',
  cancel: 'Cancel',
  created: 'Project created',
  untitled: 'Untitled',
  save: 'Save',
  saved: 'Saved',
  saving: 'Saving…',
  delete: 'Delete',
  confirmDelete: 'Delete this document?',
  ai: 'Assistant',
  polish: 'Polish',
  continue: 'Continue',
  outline: 'Outline',
  compress: 'Compress',
  expand: 'Expand',
  research: 'Research',
  spark: 'Sparks',
  insert: 'Append',
  replaceSel: 'Replace selection',
  sendChat: 'Send to chat',
  applying: 'Working…',
  noText: 'Select or write something first',
  aiUnavailable: 'No LLM service; use Send to chat instead.',
  empty: 'No library root. Click + to pick a folder (e.g. E:\\剧本).',
  emptyCta: 'Add E:\\剧本',
  noProjects: 'No project.md under this root. You can still open any .md / .fountain.',
  focus: 'Focus',
  chars: 'chars',
  words: 'Words',
  openAi: 'AI',
  closeAi: 'Hide AI',
  gates: 'Gates',
  gateShort: 'Gate',
  runGates: 'Run gates',
  gatesPass: 'All pass',
  gatesFail: '{n} failed',
  gatesNone: 'Unsupported type',
  gatesIdle: 'Open .md / .fountain to run gates',
  saveAsNew: 'Save as v+1',
  bumpHint: 'Create -v(N+1) keeping the old draft',
  hideLib: 'Hide library',
  showLib: 'Show library',
  search: 'Search files…',
  openLatest: 'Open latest',
  isHistory: 'History',
  isLatest: 'Current',
  versions: 'Versions',
  comparePrev: 'Diff vs prev',
  closeDiff: 'Close diff',
  diffTitle: 'Diff vs previous',
  reviewFix: 'Fix from review',
  ledger: 'Ledger',
  ledgerHook: 'Chapter hook',
  ledgerFores: 'Open foreshadows',
  ledgerReview: 'Latest review',
  ledgerTimeline: 'Timeline tail',
  ledgerNone: 'Open a project file',
  addRoot: 'Add library…',
  switchRoot: 'Library',
  removeRoot: 'Remove',
  missing: 'Missing',
  unsaved: 'Unsaved',
  pathLabel: 'Path',
  suggestRoot: 'Suggested library:',
  addSuggest: 'Add',
  copyPath: 'Copy path',
  copied: 'Copied',
}


export function pickLocale() {
  try {
    const lang = String(navigator.language || '').toLowerCase()
    return lang.startsWith('zh') ? zh : en
  } catch {
    return zh
  }
}

export const T = pickLocale()
export { zh, en }
