# Build installer, then publish to GitHub Releases (or print manual upload commands).
# Usage: powershell -ExecutionPolicy Bypass -File release.ps1
# Publish is automatic when the `gh` CLI is installed AND authenticated
# (GH_TOKEN set, or `gh auth login` done). Otherwise it prints the equivalent
# manual commands, so the script is still usable without credentials.
# Keep this file ASCII-only (see the note in install-update.ps1).
$ErrorActionPreference = 'Stop'
$proj = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $proj

$owner = 'yuanzhoucanxiang'
$repo = 'dsh-desktop'
# Read the version with node, NEVER with PowerShell's ConvertFrom-Json:
# PS 5.1 parses package.json (non-ASCII description) as ANSI/GBK -> invalid JSON
# (same pitfall documented in build.ps1; bit the release flow at v0.1.20).
$ver = (& node -p "require('./package.json').version").Trim()
$tag = "v$ver"
$exe = "dsh-desktop-$ver-setup.exe"

# 1. build (self-contained runtime + NSIS installer + latest.yml)
& powershell -ExecutionPolicy Bypass -File "$proj\build.ps1"
if ($LASTEXITCODE -ne 0) { throw "build.ps1 failed (exit $LASTEXITCODE)" }

# 2. publish (mac dmg is built and uploaded automatically by GitHub Actions once the tag is pushed)
$assets = @("dist\$exe", "dist\latest.yml", "dist\$exe.blockmap")

$gh = Get-Command gh -ErrorAction SilentlyContinue
$authed = $false
if ($gh -and $env:GH_TOKEN) {
  $authed = $true
} elseif ($gh) {
  gh auth status *> $null
  if ($LASTEXITCODE -eq 0) { $authed = $true }
}

if ($authed) {
  Write-Host ""
  Write-Host "publishing $tag to $owner/$repo via gh ..."
  Write-Host "NOTE: make sure your changes are committed and pushed first (the tag points at a pushed commit)."
  # If the release already exists, create fails and we simply upload with --clobber (idempotent-ish).
  gh release create $tag --repo "$owner/$repo" --title "DeepSeek Harness Desktop $ver" --notes "Release $ver" *> $null
  foreach ($a in $assets) {
    gh release upload $tag --repo "$owner/$repo" --clobber $a
    if ($LASTEXITCODE -ne 0) { throw "gh release upload failed for $a" }
  }
  Write-Host "published: https://github.com/$owner/$repo/releases/tag/$tag"
} else {
  Write-Host ""
  Write-Host "=== GitHub Release: upload these dist/ files to tag $tag ==="
  Write-Host ""
  Write-Host "--- via gh CLI (or run: gh auth login, then re-run this script for auto-publish) ---"
  Write-Host "gh release create $tag --repo $owner/$repo --title `"DeepSeek Harness Desktop $ver`" --notes `"Release $ver`""
  Write-Host "gh release upload $tag --repo $owner/$repo --clobber `"dist\$exe`" `"dist\latest.yml`" `"dist\$exe.blockmap`""
  Write-Host ""
  Write-Host "--- or via web ---"
  Write-Host "https://github.com/$owner/$repo/releases/new?tag=$tag"
  Write-Host ""
  Write-Host "NOTE: version must match package.json; bump before releasing. latest.yml is generated by build.ps1."
}
