/**
 * 写作模式样式源码（构建时随客户端一起打进 client.js）。
 * ensureWritingCss() 幂等注入 <style id="dsh-writing-mode-css">；
 * entry 在模块加载期调用一次，与原行为时序一致。
 */
export const CSS = [
  /* 写作台打开：藏自有浮钮 + PALIS 浮钮/状态条，避免叠层 */
  'html[data-writing-mode="on"] #dsh-writing-mode-float{display:none !important;}',
  'html[data-writing-mode="on"] .ptp-float{display:none !important;}',
  'html[data-writing-mode="on"] #palis-theme-float,',
  'html[data-writing-mode="on"] #palis-float,',
  'html[data-writing-mode="on"] .palis-float,',
  'html[data-writing-mode="on"] .ptp-status,',
  'html[data-writing-mode="on"] #palis-status,',
  'html[data-writing-mode="on"] [data-palis-status],',
  'html[data-writing-mode="on"] .palis-statusbar{display:none !important;}',

  '.dshWmFloat{',
  '  position:fixed;right:18px;bottom:18px;z-index:95;',
  '  display:inline-flex;align-items:center;gap:6px;',
  '  height:34px;padding:0 14px;border-radius:999px;cursor:pointer;',
  '  border:1px solid var(--dsw-alias-border-l2);',
  '  background:var(--dsw-alias-bg-layer-3);',
  '  color:var(--dsw-alias-label-secondary);',
  '  font:inherit;font-size:12px;line-height:1;',
  '  box-shadow:0 4px 16px rgba(0,0,0,.16);',
  '}',
  '.dshWmFloat:hover{color:var(--dsw-alias-label-primary);border-color:var(--dsw-alias-brand-primary);}',

  /* 压住 PALIS 状态条 / 更高层 UI */
  '.dshWmRoot{',
  '  position:fixed;top:0;left:0;right:0;bottom:0;',
  '  z-index:2000 !important;',
  '  display:flex;flex-direction:column;',
  '  background:var(--dsw-alias-bg-base);',
  '  color:var(--dsw-alias-label-primary);',
  '  font-family:var(--dsw-font-sans,var(--ds-font-family-sans,system-ui,sans-serif));',
  '  overflow:hidden;',
  '}',

  /* 顶栏右侧让出系统窗口控件（Win 最小化/最大化/关闭约 120–140px） */
  '.dshWmBar{',
  '  display:flex;align-items:center;gap:8px;',
  '  height:52px;padding:0 148px 0 16px;flex:none;',
  '  border-bottom:1px solid var(--dsw-alias-border-l2);',
  '  background:var(--dsw-alias-bg-layer-1);',
  '  box-sizing:border-box;',
  '}',
  '.dshWmBrand{',
  '  font-size:13px;font-weight:650;color:var(--dsw-alias-label-primary);',
  '  padding-right:10px;margin-right:2px;',
  '  border-right:1px solid var(--dsw-alias-border-l2);',
  '  flex:none;',
  '}',
  '.dshWmBarGroup{display:flex;align-items:center;gap:6px;min-width:0;flex:none;}',
  '.dshWmBarSpacer{flex:1;min-width:16px;}',
  '.dshWmSelect{',
  '  font:inherit;font-size:12px;padding:6px 10px;border-radius:8px;',
  '  border:1px solid var(--dsw-alias-border-l2);',
  '  background:var(--dsw-alias-bg-layer-2);color:var(--dsw-alias-label-primary);',
  '  max-width:160px;',
  '}',
  '.dshWmBtn{',
  '  font:inherit;font-size:12px;padding:6px 12px;border-radius:8px;cursor:pointer;',
  '  background:transparent;color:var(--dsw-alias-label-secondary);',
  '  border:1px solid var(--dsw-alias-border-l2);',
  '  white-space:nowrap;flex:none;',
  '}',
  '.dshWmBtn:hover{color:var(--dsw-alias-label-primary);border-color:var(--dsw-alias-brand-primary);}',
  '.dshWmBtn:disabled{opacity:.4;cursor:default;}',
  '.dshWmBtn.is-primary{',
  '  background:var(--dsw-alias-button-primary-fill);',
  '  color:var(--dsw-alias-label-primary-foreground);border-color:transparent;',
  '}',
  '.dshWmBtn.is-ghost{border-color:transparent;padding-left:8px;padding-right:8px;}',
  '.dshWmBtn.is-danger{color:var(--dsw-alias-state-error-primary);}',
  '.dshWmBtn.is-on{',
  '  background:color-mix(in srgb,var(--dsw-alias-brand-primary) 14%,transparent);',
  '  border-color:var(--dsw-alias-brand-primary);',
  '  color:var(--dsw-alias-label-primary);',
  '}',

  '.dshWmBody{flex:1;display:flex;min-height:0;}',
  '.dshWmSide{',
  '  width:248px;flex:none;display:flex;flex-direction:column;min-height:0;',
  '  border-right:1px solid var(--dsw-alias-border-l2);',
  '  background:var(--dsw-alias-bg-layer-1);',
  '}',
  '.dshWmSide.is-ai{width:clamp(360px,34vw,560px);border-right:none;border-left:1px solid var(--dsw-alias-border-l2);}',
  '.dshWmCompanion{display:flex;flex-direction:column;flex:1;min-height:0;padding:0 16px 16px;gap:12px;}',
  '.dshWmConversationHead{display:flex;align-items:center;justify-content:space-between;gap:8px;font-size:12px;color:var(--dsw-alias-label-tertiary);}.dshWmConversationHead>span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;}',
  '.dshWmQuiet{border:0;background:transparent;color:var(--dsw-alias-label-secondary);font:inherit;font-size:12px;padding:5px 2px;cursor:pointer;white-space:nowrap;}.dshWmQuiet:hover{color:var(--dsw-alias-label-primary);}.dshWmQuiet:disabled{opacity:.4;cursor:default;}',
  '.dshWmConversation{flex:1;min-height:0;overflow:auto;overscroll-behavior:contain;padding:8px 2px;scrollbar-width:thin;}',
  '.dshWmCompanionEmpty{padding:clamp(30px,12vh,130px) 16px 30px;color:var(--dsw-alias-label-secondary);line-height:1.9;white-space:pre-line;}.dshWmCompanionEmpty h3{font-size:21px;font-weight:500;margin:16px 0 8px;color:var(--dsw-alias-label-primary);}.dshWmCompanionEmpty p{font-size:13px;margin:0;}.dshWmCompanionMark{font-size:24px;opacity:.6;}',
  '.dshWmMessage{margin:0 0 26px;}.dshWmMessageWho{display:block;font-size:11px;color:var(--dsw-alias-label-tertiary);margin-bottom:8px;}.dshWmMessageText{font-size:14px;line-height:1.9;white-space:pre-wrap;overflow-wrap:anywhere;user-select:text;}.dshWmMessage.is-user{padding:12px 14px;border-radius:10px;background:var(--dsw-alias-bg-layer-2);}.dshWmMessage.is-error{color:var(--dsw-alias-state-error-primary);}',
  '.dshWmMarkdown{white-space:normal;min-width:0;}.dshWmMarkdown>:first-child{margin-top:0;}.dshWmMarkdown>:last-child{margin-bottom:0;}',
  '.dshWmMarkdown p{margin:0 0 .85em;white-space:pre-wrap;}.dshWmMarkdown h1,.dshWmMarkdown h2,.dshWmMarkdown h3,.dshWmMarkdown h4,.dshWmMarkdown h5,.dshWmMarkdown h6{font-size:1.08em;line-height:1.6;margin:1.3em 0 .55em;font-weight:600;}',
  '.dshWmMarkdown ul,.dshWmMarkdown ol{padding-left:1.5em;margin:.6em 0 1em;}.dshWmMarkdown li{margin:.3em 0;}.dshWmMarkdown li>p{margin:.3em 0;}.dshWmMarkdown blockquote{margin:.8em 0;padding:.15em 0 .15em 1em;border-left:2px solid var(--dsw-alias-border-l2);color:var(--dsw-alias-label-secondary);}',
  '.dshWmMarkdown a{color:inherit;text-decoration:underline;text-underline-offset:3px;overflow-wrap:anywhere;}.dshWmMarkdown a:focus-visible,.dshWmMarkdownTable:focus-visible{outline:2px solid currentColor;outline-offset:3px;}',
  '.dshWmMarkdown code{font-size:.9em;font-family:ui-monospace,Consolas,monospace;background:var(--dsw-alias-bg-layer-2);border-radius:4px;padding:.1em .3em;}.dshWmMarkdown pre{max-width:100%;overflow:auto;white-space:pre;tab-size:2;padding:12px;border-radius:8px;background:var(--dsw-alias-bg-layer-2);line-height:1.6;}.dshWmMarkdown pre code{padding:0;background:none;}',
  '.dshWmMarkdownTable{max-width:100%;overflow:auto;margin:.8em 0;}.dshWmMarkdown table{border-collapse:collapse;font-size:.92em;min-width:100%;}.dshWmMarkdown th,.dshWmMarkdown td{padding:6px 10px;border:1px solid var(--dsw-alias-border-l2);text-align:left;vertical-align:top;}.dshWmMarkdown hr{border:0;border-top:1px solid var(--dsw-alias-border-l2);margin:1.2em 0;}',
  '.dshWmActivity{font-size:12px;color:var(--dsw-alias-label-secondary);margin:8px 0;overflow-wrap:anywhere;}.dshWmActivity pre,.dshWmReference pre{white-space:pre-wrap;overflow-wrap:anywhere;max-height:180px;overflow:auto;font-family:inherit;font-size:12px;line-height:1.6;}.dshWmActivity summary,.dshWmReference summary{cursor:pointer;}',
  '.dshWmRequest{padding:12px;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;font-size:12px;display:flex;flex-direction:column;align-items:flex-start;gap:6px;margin:12px 0;}.dshWmThinking{font-size:12px;color:var(--dsw-alias-label-secondary);padding:10px 0;}',
  '.dshWmCompanionError{padding:10px;font-size:12px;line-height:1.6;color:var(--dsw-alias-state-error-primary);overflow-wrap:anywhere;max-height:120px;overflow:auto;}',
  '.dshWmMemory{border-bottom:1px solid var(--dsw-alias-border-l2);max-height:220px;display:flex;flex-direction:column;}',
  '.dshWmMemoryList{overflow:auto;flex:1;padding:0 10px 8px;}',
  '.dshWmMemoryItem{padding:6px 8px;margin-bottom:6px;border-radius:8px;background:var(--dsw-alias-bg-layer-2);border:1px solid var(--dsw-alias-border-l2);font-size:12px;}',
  '.dshWmMemoryItem.is-retracted{opacity:.55;}',
  '.dshWmMemoryItem.is-resolved{opacity:.75;}',
  '.dshWmMemoryMeta{display:flex;gap:6px;margin-bottom:2px;font-size:10px;color:var(--dsw-alias-label-tertiary);}',
  '.dshWmMemoryKind{font-weight:700;color:var(--dsw-alias-label-secondary);}',
  '.dshWmMemoryText{line-height:1.45;color:var(--dsw-alias-label-primary);}',
  '.dshWmMemoryActions{display:flex;gap:6px;margin-top:4px;}',
  // P3：备忘完整操作（候选/编辑/历史/审计）与当轮参考面板
  '.dshWmMemoryCompose{flex-shrink:0;}',
  '.dshWmMemoryKind{background:transparent;border:1px solid var(--dsw-alias-border-l2);border-radius:6px;color:var(--dsw-alias-label-secondary);font-size:11px;padding:2px 4px;}',
  '.dshWmMemorySource{color:var(--dsw-alias-label-tertiary);}',
  '.dshWmMemoryNote{font-size:10px;line-height:1.5;color:var(--dsw-alias-label-tertiary);padding:2px 10px 4px;}',
  '.dshWmMemoryEdit{display:flex;align-items:center;gap:6px;}',
  '.dshWmMemoryHistory{margin-top:6px;border-top:1px dashed var(--dsw-alias-border-l2);padding-top:6px;}',
  '.dshWmMemoryHistoryRow{margin-bottom:6px;}.dshWmMemoryHistoryRow:last-child{margin-bottom:0;}',
  '.dshWmMemoryDiff{font-size:11px;line-height:1.5;}.dshWmMemoryDiff .is-del{color:var(--dsw-alias-state-error-primary);}.dshWmMemoryDiff .is-add{color:var(--dsw-alias-state-success-primary);}',
  '.dshWmMemoryWorkspace{flex:0 1 auto;min-height:0;max-height:45vh;overflow:auto;overscroll-behavior:contain;}',
  '.dshWmMemoryWorkspace .dshWmMemory{max-height:180px;}',
  '.dshWmWorldPanel{border-bottom:1px solid var(--dsw-alias-border-l2);padding:8px 10px 12px;display:flex;flex-direction:column;gap:6px;font-size:12px;min-height:120px;flex-shrink:0;overscroll-behavior:contain;}',
  '.dshWmWorldPanel pre{white-space:pre-wrap;overflow-wrap:anywhere;max-height:180px;overflow:auto;margin:6px 0;}',
  '.dshWmWorldPanel button{margin:3px 4px 3px 0;white-space:normal;}',
  '.dshWmWorldHead{display:flex;align-items:center;gap:8px;font-weight:600;color:var(--dsw-alias-label-primary);}',
  '.dshWmWorldSub{font-weight:400;font-size:11px;color:var(--dsw-alias-label-tertiary);}',
  '.dshWmWorldScope{max-height:96px;overflow:auto;display:flex;flex-direction:column;gap:4px;}',
  '.dshWmWorldMsg{font-size:11px;line-height:1.4;color:var(--dsw-alias-label-secondary);background:var(--dsw-alias-bg-layer-2);border:1px solid var(--dsw-alias-border-l2);border-radius:6px;padding:4px 6px;}',
  '.dshWmWorldPanel input,.dshWmWorldPanel textarea{width:100%;box-sizing:border-box;border:1px solid var(--dsw-alias-border-l2);border-radius:6px;background:var(--dsw-alias-bg-layer-1);color:var(--dsw-alias-label-primary);font:inherit;font-size:12px;padding:4px 6px;}',
  '.dshWmWorldPanel label{font-size:11px;color:var(--dsw-alias-label-tertiary);margin-top:4px;}',
  '.dshWmWorldCard{border:1px solid var(--dsw-alias-border-l2);border-radius:8px;padding:8px;background:var(--dsw-alias-bg-layer-2);display:flex;flex-direction:column;gap:4px;}',
  '.dshWmWorldCardTitle{font-weight:600;}',
  '.dshWmWorldOps{display:flex;gap:6px;flex-wrap:wrap;margin-top:4px;}',
  '.dshWmWorldNotice{font-size:11px;color:var(--dsw-alias-label-secondary);line-height:1.5;}',
  '.dshWmWorldSrc{font-size:10px;color:var(--dsw-alias-label-tertiary);}',
  '.dshWmWorldRaw{max-height:120px;overflow:auto;white-space:pre-wrap;font-size:11px;border:1px dashed var(--dsw-alias-border-l2);border-radius:6px;padding:6px;}',
  '.dshWmWorldList{max-height:140px;overflow:auto;}',
  '.dshWmWorldItem{padding:4px 6px;border-radius:6px;margin-bottom:4px;background:var(--dsw-alias-bg-layer-2);border:1px solid var(--dsw-alias-border-l2);}',
  '.dshWmWorldItem.proposed{opacity:.85;}',
  '.dshWmWorldItem.retracted{opacity:.5;}',
  '.dshWmMessage.is-world-selected{outline:1px dashed var(--dsw-alias-label-tertiary);outline-offset:2px;}',
  '.dshWmMessageAction.is-on{color:var(--dsw-alias-state-success-primary);}',
  '.dshWmMessageAction{margin-top:4px;font-size:11px;}',
  '.dshWmDraftCandidates{display:flex;flex-direction:column;gap:4px;border-bottom:1px dashed var(--dsw-alias-border-l2);padding-bottom:8px;margin-bottom:8px;}',
  '.dshWmDraftCandidate{display:flex;align-items:center;gap:6px;flex-wrap:wrap;}',
  '.dshWmDraftPreview pre{white-space:pre-wrap;overflow-wrap:anywhere;max-height:160px;overflow:auto;font-family:inherit;font-size:12px;line-height:1.6;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;padding:6px 8px;background:var(--dsw-alias-bg-layer-2);}',
  '.dshWmContext{display:flex;flex-direction:column;gap:4px;padding:6px 0 2px;}',
  '.dshWmContextSwitch{margin-left:auto;display:flex;align-items:center;gap:4px;font-size:11px;color:var(--dsw-alias-label-tertiary);}',
  '.dshWmContextPanel{max-height:200px;overflow:auto;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;padding:6px 8px;background:var(--dsw-alias-bg-layer-2);}',
  '.dshWmContextItem{display:flex;align-items:flex-start;gap:6px;font-size:11px;line-height:1.5;padding:3px 0;}',
  '.dshWmContextText{color:var(--dsw-alias-label-primary);overflow-wrap:anywhere;}',
  '.dshWmContextState{margin-left:auto;font-size:10px;color:var(--dsw-alias-label-tertiary);white-space:nowrap;}',
  '.dshWmContextQuestions{margin-top:4px;border-top:1px dashed var(--dsw-alias-border-l2);padding-top:4px;}',
  '.dshWmCompose{border:1px solid var(--dsw-alias-border-l2);border-radius:12px;background:var(--dsw-alias-bg-layer-1);padding:12px;}.dshWmCompose:focus-within{border-color:var(--dsw-alias-label-tertiary);}.dshWmChatInput{display:block;box-sizing:border-box;width:100%;min-height:88px;max-height:200px;resize:vertical;border:0;outline:none;background:transparent;color:var(--dsw-alias-label-primary);font-family:inherit;font-size:14px;line-height:1.7;}.dshWmChatInput::placeholder{color:var(--dsw-alias-label-tertiary);}',
  '.dshWmComposeFoot{display:flex;align-items:center;gap:8px;margin-top:8px;}.dshWmInputHint{margin-left:auto;font-size:10px;color:var(--dsw-alias-label-tertiary);}.dshWmSend{margin-left:auto;flex-shrink:0;width:30px;height:30px;border:0;border-radius:8px;background:var(--dsw-alias-label-primary);color:var(--dsw-alias-bg-base);font-size:21px;cursor:pointer;}.dshWmSend:disabled{opacity:.25;cursor:default;}',
  '.dshWmReference{display:flex;align-items:start;gap:8px;border-bottom:1px solid var(--dsw-alias-border-l2);padding-bottom:10px;margin-bottom:10px;font-size:12px;color:var(--dsw-alias-label-secondary);}.dshWmReference details{flex:1;min-width:0;}',
  '.dshWmSide.is-ai>.dshWmSideHead{gap:22px;padding:14px 18px 10px;}.dshWmTab{font:inherit;font-size:13px;padding:4px 0 8px;background:none;border:0;border-bottom:2px solid transparent;color:var(--dsw-alias-label-tertiary);cursor:pointer;}.dshWmTab.is-on{color:var(--dsw-alias-label-primary);border-bottom-color:var(--dsw-alias-label-primary);}',
  '@media(max-width:1250px){.dshWmInputHint{display:none;}}',

  '.dshWmSideHead{',
  '  display:flex;align-items:center;gap:6px;padding:12px 12px 8px;flex:none;',
  '  font-size:11px;font-weight:600;letter-spacing:.04em;color:var(--dsw-alias-label-tertiary);',
  '}',
  '.dshWmList{flex:1;overflow:auto;padding:4px 10px 20px;}',
  '.dshWmProj{margin-bottom:12px;}',
  '.dshWmProjToggle{',
  '  display:flex;align-items:center;gap:6px;width:100%;',
  '  padding:8px 8px 4px;border:none;background:transparent;cursor:pointer;',
  '  font:inherit;font-size:13px;font-weight:600;color:var(--dsw-alias-label-primary);',
  '  text-align:left;',
  '}',
  '.dshWmProjToggle:hover{color:var(--dsw-alias-brand-primary);}',
  '.dshWmProjChev{font-size:10px;color:var(--dsw-alias-label-tertiary);transition:transform .12s;flex:none;}',
  '.dshWmProjChev.is-open{transform:rotate(90deg);}',
  '.dshWmFolder{',
  '  font-size:10px;font-weight:700;letter-spacing:.08em;text-transform:uppercase;',
  '  color:var(--dsw-alias-label-tertiary);padding:8px 8px 3px;',
  '}',
  '.dshWmSearch{',
  '  width:100%;margin:0 0 8px;padding:7px 10px;border-radius:8px;',
  '  border:1px solid var(--dsw-alias-border-l2);',
  '  background:var(--dsw-alias-bg-layer-2);color:var(--dsw-alias-label-primary);',
  '  font:inherit;font-size:12px;outline:none;box-sizing:border-box;',
  '}',
  '.dshWmSearch:focus{border-color:var(--dsw-alias-brand-primary);}',
  '.dshWmItem{',
  '  display:block;width:100%;text-align:left;cursor:pointer;',
  '  padding:7px 8px;margin-bottom:2px;border-radius:8px;border:1px solid transparent;',
  '  background:transparent;color:var(--dsw-alias-label-primary);',
  '  font:inherit;font-size:12.5px;line-height:1.35;box-sizing:border-box;',
  '}',
  '.dshWmItem:hover{background:var(--dsw-alias-interactive-bg-hover);}',
  '.dshWmItem.is-on{',
  '  border-color:color-mix(in srgb,var(--dsw-alias-brand-primary) 50%,transparent);',
  '  background:color-mix(in srgb,var(--dsw-alias-brand-primary) 12%,transparent);',
  '}',
  '.dshWmItemRow{display:flex;align-items:baseline;gap:4px;}',
  '.dshWmItemTitle{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;flex:1;min-width:0;}',
  '.dshWmItemMeta{display:block;font-size:10px;color:var(--dsw-alias-label-tertiary);margin-top:2px;}',
  '.dshWmVer{',
  '  display:inline-block;margin-left:6px;padding:0 5px;border-radius:4px;flex:none;',
  '  font-size:10px;font-weight:700;line-height:16px;',
  '  background:color-mix(in srgb,var(--dsw-alias-brand-primary) 16%,transparent);',
  '  color:var(--dsw-alias-brand-primary);',
  '}',
  '.dshWmVer.is-hist{background:var(--dsw-alias-bg-layer-2);color:var(--dsw-alias-label-tertiary);}',

  '.dshWmMain{flex:1;display:flex;flex-direction:column;min-width:0;min-height:0;}',
  '.dshWmDocChrome{flex:none;padding:24px 32px 0;max-width:820px;margin:0 auto;width:100%;box-sizing:border-box;}',
  '.dshWmPathRow{display:flex;align-items:center;gap:8px;font-size:11px;color:var(--dsw-alias-label-tertiary);flex-wrap:wrap;}',
  '.dshWmPathText{flex:1;min-width:120px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;}',
  '.dshWmDocName{margin:10px 0 4px;font-size:22px;font-weight:650;line-height:1.3;}',
  '.dshWmDocRule{height:1px;margin:12px 0 0;background:var(--dsw-alias-border-l2);}',
  '.dshWmHistBanner{',
  '  display:flex;align-items:center;gap:10px;margin-top:10px;padding:8px 12px;',
  '  border-radius:8px;border:1px solid var(--dsw-alias-border-l2);',
  '  background:color-mix(in srgb,var(--dsw-alias-state-warning-primary,#c9a227) 12%,transparent);',
  '  font-size:12px;',
  '}',
  '.dshWmVerBar{display:flex;flex-wrap:wrap;gap:6px;align-items:center;margin-top:10px;}',
  '.dshWmVerBarLabel{font-size:10px;font-weight:700;letter-spacing:.06em;color:var(--dsw-alias-label-tertiary);}',
  '.dshWmVerChip{',
  '  font:inherit;font-size:11px;padding:3px 8px;border-radius:999px;cursor:pointer;',
  '  border:1px solid var(--dsw-alias-border-l2);background:transparent;',
  '  color:var(--dsw-alias-label-secondary);',
  '}',
  '.dshWmVerChip:hover{border-color:var(--dsw-alias-brand-primary);}',
  '.dshWmVerChip.is-on{',
  '  border-color:var(--dsw-alias-brand-primary);',
  '  background:color-mix(in srgb,var(--dsw-alias-brand-primary) 16%,transparent);',
  '  color:var(--dsw-alias-label-primary);font-weight:600;',
  '}',
  '.dshWmEditorWrap{flex:1;min-height:0;display:flex;justify-content:center;}',
  '.dshWmEditor{',
  '  flex:1;min-height:0;max-width:820px;width:100%;',
  '  resize:none;outline:none;border:none;box-sizing:border-box;',
  '  padding:20px 32px 48px;',
  '  font-family:"Source Han Serif SC","Noto Serif SC","Songti SC","SimSun",Georgia,serif;',
  '  font-size:var(--dsh-wm-font-size,17px);',
  '  line-height:var(--dsh-wm-line-height,1.95);letter-spacing:.02em;',
  '  color:var(--dsw-alias-label-primary);background:transparent;',
  '}',
  '.dshWmStatus{',
  '  flex:none;height:32px;display:flex;align-items:center;gap:10px;padding:0 16px;',
  '  border-top:1px solid var(--dsw-alias-border-l2);',
  '  background:var(--dsw-alias-bg-layer-1);',
  '  font-size:11px;color:var(--dsw-alias-label-tertiary);',
  '}',
  '.dshWmStatus .dot{width:6px;height:6px;border-radius:50%;background:var(--dsw-alias-label-tertiary);}',
  '.dshWmStatus .dot.is-dirty{background:var(--dsw-alias-state-warning-primary,#c9a227);}',
  '.dshWmStatus .dot.is-saved{background:var(--dsw-alias-state-success-primary);}',
  '.dshWmStatusSep{opacity:.35;}',

  '.dshWmAiBody{',
  '  flex:1;display:flex;flex-direction:column;min-height:0;',
  '  padding:8px 12px 20px;gap:8px;overflow:auto;',
  '}',
  '.dshWmAiSection{display:flex;flex-direction:column;gap:8px;}',
  '.dshWmAiSectionTitle{font-size:10px;font-weight:700;letter-spacing:.08em;text-transform:uppercase;color:var(--dsw-alias-label-tertiary);}',
  '.dshWmAiMain{flex:1;min-height:0;display:flex;flex-direction:column;gap:8px;}',
  '.dshWmAiActions{display:flex;flex-wrap:wrap;gap:6px;}',
  '.dshWmAiOut{',
  '  flex:1;min-height:140px;overflow:auto;padding:12px;border-radius:10px;',
  '  border:1px solid var(--dsw-alias-border-l2);',
  '  background:var(--dsw-alias-bg-layer-2);',
  '  font-size:13px;line-height:1.7;white-space:pre-wrap;word-break:break-word;',
  '}',
  '.dshWmAiHint{font-size:11px;color:var(--dsw-alias-label-tertiary);line-height:1.5;}',
  '.dshWmSec{display:flex;flex-direction:column;gap:6px;}',
  '.dshWmSecToggle{',
  '  display:flex;align-items:center;gap:6px;width:100%;',
  '  padding:6px 0;border:none;background:transparent;cursor:pointer;',
  '  font:inherit;font-size:11px;font-weight:700;letter-spacing:.06em;',
  '  text-transform:uppercase;color:var(--dsw-alias-label-tertiary);text-align:left;',
  '}',
  '.dshWmSecToggle:hover{color:var(--dsw-alias-label-primary);}',
  '.dshWmSecBadge{',
  '  margin-left:auto;font-size:10px;font-weight:600;letter-spacing:0;text-transform:none;',
  '  padding:1px 6px;border-radius:999px;',
  '  background:var(--dsw-alias-bg-layer-2);color:var(--dsw-alias-label-secondary);',
  '}',
  '.dshWmSecBadge.is-pass{color:var(--dsw-alias-state-success-primary);}',
  '.dshWmSecBadge.is-fail{color:var(--dsw-alias-state-error-primary);}',
  '.dshWmGateList{display:flex;flex-direction:column;gap:3px;}',
  '.dshWmGateRow{',
  '  display:flex;gap:8px;align-items:baseline;font-size:12px;line-height:1.45;',
  '  padding:5px 8px;border-radius:8px;background:var(--dsw-alias-bg-layer-2);',
  '}',
  '.dshWmGateRow .ok{color:var(--dsw-alias-state-success-primary);font-weight:700;font-size:10px;flex:none;width:34px;}',
  '.dshWmGateRow .bad{color:var(--dsw-alias-state-error-primary);font-weight:700;font-size:10px;flex:none;width:34px;}',
  '.dshWmGateLabel{color:var(--dsw-alias-label-primary);flex:none;min-width:5em;}',
  '.dshWmGateDetail{color:var(--dsw-alias-label-tertiary);flex:1;word-break:break-word;font-size:11px;}',
  '.dshWmLedger{',
  '  display:flex;flex-direction:column;gap:6px;font-size:12px;line-height:1.55;',
  '  padding:8px 10px;border-radius:10px;',
  '  border:1px solid var(--dsw-alias-border-l2);background:var(--dsw-alias-bg-layer-2);',
  '  color:var(--dsw-alias-label-secondary);',
  '}',
  '.dshWmLedgerRow{display:flex;gap:8px;}',
  '.dshWmLedgerK{flex:none;min-width:4.5em;color:var(--dsw-alias-label-tertiary);font-size:11px;}',
  '.dshWmLedgerV{flex:1;word-break:break-word;color:var(--dsw-alias-label-primary);}',
  '.dshWmDiff{',
  '  flex:none;max-height:36%;overflow:auto;',
  '  border-top:1px solid var(--dsw-alias-border-l2);',
  '  background:var(--dsw-alias-bg-layer-1);padding:8px 12px;',
  '}',
  '.dshWmDiffHead{display:flex;align-items:center;gap:8px;margin-bottom:6px;font-size:11px;color:var(--dsw-alias-label-tertiary);}',
  '.dshWmDiffLine{',
  '  font-family:var(--ds-font-family-code,monospace);font-size:11px;line-height:1.55;',
  '  white-space:pre-wrap;word-break:break-word;padding:1px 6px;border-radius:3px;',
  '}',
  '.dshWmDiffLine.add{background:color-mix(in srgb,var(--dsw-alias-state-success-primary) 14%,transparent);}',
  '.dshWmDiffLine.del{background:color-mix(in srgb,var(--dsw-alias-state-error-primary) 12%,transparent);text-decoration:line-through;}',
  '.dshWmDiffLine.ctx{color:var(--dsw-alias-label-tertiary);}',
  '.dshWmWelcome{',
  '  flex:1;display:flex;flex-direction:column;align-items:center;justify-content:center;',
  '  gap:14px;padding:40px;text-align:center;color:var(--dsw-alias-label-secondary);',
  '}',
  '.dshWmWelcomeTitle{font-size:22px;font-weight:650;color:var(--dsw-alias-label-primary);}',
  '.dshWmWelcomeBody{font-size:13px;line-height:1.7;max-width:420px;}',
  '.dshWmEmpty{padding:16px;color:var(--dsw-alias-label-tertiary);font-size:12.5px;line-height:1.6;}',
  '.dshWmFlash{',
  '  position:absolute;left:50%;transform:translateX(-50%);top:60px;z-index:20;',
  '  max-width:70%;padding:8px 14px;border-radius:8px;',
  '  background:color-mix(in srgb,var(--dsw-alias-bg-layer-3) 95%,transparent);',
  '  border:1px solid var(--dsw-alias-border-l2);',
  '  color:var(--dsw-alias-label-primary);font-size:12px;',
  '  box-shadow:0 4px 16px rgba(0,0,0,.2);',
  '}',

  'body[data-writing-focus="1"] .dshWmSide{display:none;}',
  'body[data-writing-focus="1"] .dshWmEditor{',
  '  font-size:calc(var(--dsh-wm-font-size,17px) + 1px);',
  '  line-height:calc(var(--dsh-wm-line-height,1.95) + 0.1);max-width:720px;',
  '}',
  'body[data-writing-focus="1"] .dshWmDocChrome{max-width:720px;}',
  'html[data-writing-mode] body[data-writing-lib="0"] .dshWmSide:not(.is-ai){display:none;}',
].join('\n')

const TAG = 'dsh-writing-mode-css'

export function ensureWritingCss() {
  if (typeof document !== 'undefined' && !document.getElementById(TAG)) {
    const tag = document.createElement('style')
    tag.id = TAG
    tag.textContent = CSS
    document.head.appendChild(tag)
  }
}
