/**
 * 写作模式样式源码（构建时随客户端一起打进 client.js）。
 * ensureWritingCss() 幂等注入 <style id="dsh-writing-mode-css">；
 * entry 在模块加载期调用一次，与原行为时序一致。
 */
export const CSS = [
  /* B1 语义令牌层：字号 / 间距 / 圆角 / 字重 + 状态色别名。
     自带字面值，不依赖外壳 --dsw-* 是否注入。
     作用域挂 :root 而非 .dshWmRoot：写作品牌不全在根内——入口浮钮（.dshWmFloat，挂 body）、
     设置页（.dshWmSettings，走 settings.section 槽位挂在外壳设置弹层）、外壳里的入口钮
     （.dshWmBtn，侧边栏 footer / 会话顶栏槽位）都在根外，挂 .dshWmRoot 会让它们解析不到
     令牌（font-size 之类会退回 inherit）。
     状态色别名里的字面回退取自外壳调色（preload.js），仅在外壳变量缺席时生效。
     --wm-warn 引用的是外壳真名 --dsw-alias-state-warn-primary（短名）：
     早先写的 --dsw-alias-state-warning-primary 外壳从未定义，导致 warn 色永远停在 #c9a227。 */
  ':root{',
  '  --wm-text-xs:11px;--wm-text-sm:12.5px;--wm-text-md:14px;--wm-text-lg:17px;--wm-text-xl:21px;',
  '  --wm-space-1:4px;--wm-space-2:8px;--wm-space-3:12px;--wm-space-4:20px;--wm-space-5:32px;',
  '  --wm-radius-s:6px;--wm-radius-m:10px;--wm-radius-l:14px;',
  '  --wm-weight-normal:400;--wm-weight-medium:600;--wm-weight-bold:700;',
  /* G3 小字专用色：tertiary 在 layer-1/2 底上约 3.2–3.4:1（10–11px 正文读不清），
     小字号一律改用 secondary 档；大号装饰文字仍用 tertiary。 */
  '  --wm-text-dim:var(--dsw-alias-label-secondary,#8a8a8a);',
  '  --wm-ok:var(--dsw-alias-state-success-primary,#a9c2b6);--wm-err:var(--dsw-alias-state-error-primary,#c9adad);--wm-warn:var(--dsw-alias-state-warn-primary,#c9a227);',
  '}',

  /* 写作台打开：藏自有浮钮 + PALIS 浮钮/状态条，避免叠层 */
  'html[data-writing-mode="on"] #dsh-writing-mode-float{display:none !important;}',
  'html[data-writing-mode="on"] .ptp-float{display:none !important;}',
  'html[data-writing-mode="on"] #palis-theme-float,',
  'html[data-writing-mode="on"] #palis-float,',
  'html[data-writing-mode="on"] .palis-float,',
  'html[data-writing-mode="on"] .ptp-status,',
  'html[data-writing-mode="on"] #palis-status,',
  'html[data-writing-mode="on"] [data-palis-status],',
  'html[data-writing-mode="on"] .palis-statusbar{display:none !important;}',

  /* 入口收敛（2026-10-09）：可见入口只剩侧栏 footer 的一个图标钮。
     右下角浮钮默认隐藏，但**保留元素与 id** —— 既有验证/审计脚本用
     `document.getElementById('dsh-writing-mode-float').click()` 程序化进入，
     仍然照常工作；需要旧行为时给元素加 .is-shown 即可。 */
  '.dshWmFloat{',
  '  position:fixed;right:18px;bottom:18px;z-index:95;',
  '  display:none;',
  '  align-items:center;gap:6px;',
  '  height:34px;padding:0 14px;border-radius:999px;cursor:pointer;',
  '  border:1px solid var(--dsw-alias-border-l2);',
  '  background:var(--dsw-alias-bg-layer-3);',
  '  color:var(--dsw-alias-label-secondary);',
  '  font:inherit;font-size:var(--wm-text-sm);line-height:1;',
  '  box-shadow:0 4px 16px rgba(0,0,0,.16);',
  '}',
  '.dshWmFloat.is-shown{display:inline-flex;}',
  '.dshWmFloat:hover{color:var(--dsw-alias-label-primary);border-color:var(--dsw-alias-brand-primary);}',

  /* 图标入口钮（侧栏 footer 动作行 / 会话顶栏共用）。
     刻意做成「安静图标」而非整宽实底按钮：官方 footerActions 本就是一行居中动作，
     整宽 + 品牌实底会显得又大又抢眼（用户反馈的原话）。 */
  '.dshWmIconBtn{',
  '  display:inline-flex;align-items:center;justify-content:center;flex:none;',
  '  width:32px;height:32px;padding:0;border:0;border-radius:var(--wm-radius-s,8px);',
  '  background:transparent;color:var(--dsw-alias-label-secondary);',
  '  cursor:pointer;transition:background .15s ease,color .15s ease;',
  '}',
  '.dshWmIconBtn:hover{background:var(--dsw-alias-interactive-bg-hover);color:var(--dsw-alias-label-primary);}',
  '.dshWmIconBtn:focus-visible{outline:2px solid var(--dsw-alias-state-business-primary);outline-offset:-2px;}',
  '.dshWmIconBtn.is-on{color:var(--dsw-alias-brand-primary);background:color-mix(in srgb,var(--dsw-alias-brand-primary) 14%,transparent);}',
  '.dshWmIconBtn svg{display:block;}',
  '.dshWmIconBtn:disabled{opacity:.4;cursor:default;}',
  '.dshWmIconBtn:disabled:hover{background:transparent;color:var(--dsw-alias-label-secondary);}',
  /* 侧栏展开态：官方 footerActions 为整宽 flex（左起），给它留一点左内边距与 设置 行对齐观感 */
  '.dshWmIconBtn.is-wide{margin-left:2px;}',

  /* 压住 PALIS 状态条 / 更高层 UI */
  /* 顶栏避让（2026-10-08 官方桌面版适配）：官方 Electron 壳是 frameless，
     在 Windows 上用 html[data-windows-titlebar] + --dsh-windows-titlebar-height:40px
     划出一条页内标题栏（官方 AppFrame 靠 padding-top 留白），里面是
     -webkit-app-region:drag 拖拽条、侧栏开关、preload 注入的「应用/编辑」菜单，
     以及 titleBarOverlay 的原生窗口按钮（height:40）。
     本工作台用 position:fixed 相对视口定位，会**逃出** AppFrame 的 padding，
     于是把整条 40px 顶栏盖住；而拖拽区在命中测试里优先于网页内容，
     导致写模式顶栏按钮（实测 y=10..41）点不动、点击变成拖窗口。
     官方信号 --dsh-frame-top-clearance 在 darwin/Windows 桌面版分别为 48/40px，
     自研壳未定义 → 回落 0px，行为不变。 */
  '.dshWmRoot{',
  '  position:fixed;top:var(--dsh-frame-top-clearance,var(--dsh-windows-titlebar-height,0px));left:0;right:0;bottom:0;',
  '  z-index:2000 !important;',
  '  display:flex;flex-direction:column;',
  '  background:var(--dsw-alias-bg-base);',
  '  color:var(--dsw-alias-label-primary);',
  '  font-family:var(--dsw-font-sans,var(--ds-font-family-sans,system-ui,sans-serif));',
  '  overflow:hidden;',
  '}',

  /* 顶栏右侧让出系统窗口控件（Win 最小化/最大化/关闭约 120–140px）
     —— 这条只对**自研壳**成立（无边框窗口、控件画在内容区顶部）。
     官方桌面版把原生窗口按钮放在 titleBarOverlay 的 40px 条内（main.js: titleBarOverlay.height=40），
     而写模式顶栏已由上面的 --dsh-frame-top-clearance 下沉到该条之下，两者不再重叠，
     因此官方版里这 148px 让位是白留的（还会把「保存/退出写作」挤到左边）。
     用官方标记收窄，自研壳不受影响。 */
  '.dshWmBar{',
  '  display:flex;align-items:center;gap:8px;',
  '  height:52px;padding:0 148px 0 16px;flex:none;',
  '  border-bottom:1px solid var(--dsw-alias-border-l2);',
  '  background:var(--dsw-alias-bg-layer-1);',
  '  box-sizing:border-box;',
  '}',
  'html[data-windows-titlebar] .dshWmBar,html[data-platform=darwin] .dshWmBar{padding-right:16px;}',
  '.dshWmBrand{',
  '  font-size:var(--wm-text-sm);font-weight:650;color:var(--dsw-alias-label-primary);',
  '  padding-right:10px;margin-right:2px;',
  '  border-right:1px solid var(--dsw-alias-border-l2);',
  '  flex:none;',
  '}',
  '.dshWmBarGroup{display:flex;align-items:center;gap:6px;min-width:0;flex:none;}',
  /* C6 顶栏分组之间的分隔线（根/视图/保存/退出四段） */
  '.dshWmBarSep{flex:none;width:1px;height:20px;background:var(--dsw-alias-border-l2);}',
  /* E1 「辅助 ▾」下拉：菜单内容常驻 DOM，关闭时 display:none（门禁按钮点击不看可见性，照旧命中） */
  '.dshWmAux{position:relative;flex:none;display:flex;align-items:center;}',
  /* 菜单容器对命中透明：菜单是绝对定位挂在顶栏触发器下方，打开时会盖住右侧 AI 面板的
     顶部标签（文字工具/检查/写作会话）。若容器本身吃点击，点在它的空白处既不触发菜单行、
     也不触发外点关闭，那些被盖住的按钮就"按了没反应"（2026-10-09 实测复现）。 */
  '.dshWmMenu{display:none;position:absolute;top:calc(100% + 6px);right:0;z-index:40;min-width:190px;padding:var(--wm-space-1);flex-direction:column;gap:2px;border:1px solid var(--dsw-alias-border-l2);border-radius:var(--wm-radius-s);background:var(--dsw-alias-bg-layer-2);box-shadow:0 8px 24px rgba(0,0,0,.24);pointer-events:none;}',
  '.dshWmMenu.is-open{display:flex;}',
  '.dshWmMenu.is-open>*{pointer-events:auto;}',
  '.dshWmMenuRow{width:100%;text-align:left;border-color:transparent;background:transparent;}',
  '.dshWmBarSpacer{flex:1;min-width:16px;}',
  '.dshWmSelect{',
  '  font:inherit;font-size:var(--wm-text-sm);padding:6px 10px;border-radius:var(--wm-radius-m);',
  '  border:1px solid var(--dsw-alias-border-l2);',
  '  background:var(--dsw-alias-bg-layer-2);color:var(--dsw-alias-label-primary);',
  '  max-width:160px;',
  '}',
  '.dshWmBtn{',
  '  font:inherit;font-size:var(--wm-text-sm);padding:6px 12px;border-radius:var(--wm-radius-m);cursor:pointer;',
  '  background:transparent;color:var(--dsw-alias-label-secondary);',
  '  border:1px solid var(--dsw-alias-border-l2);',
  '  white-space:nowrap;flex:none;',
  '}',
  '.dshWmBtn:hover{color:var(--dsw-alias-label-primary);border-color:var(--dsw-alias-brand-primary);}',
  '.dshWmBtn:disabled{opacity:.4;cursor:default;}',
  '.dshWmBtn.is-primary{',
  '  background:var(--dsw-alias-button-primary-fill);',
  '  color:var(--dsw-alias-label-primary-foreground);border-color:transparent;',
  '}',
  '.dshWmBtn.is-ghost{border-color:transparent;padding-left:8px;padding-right:8px;}',
  '.dshWmBtn.is-danger{color:var(--wm-err);}',
  /* 选中态只有一份声明源：显式 is-on、aria-pressed、ghost+is-on（F2 后顶栏次级键多为 ghost，
     与 .dshWmBtn.is-ghost 同为 0,2,0，加进选择器列表避免靠样式表顺序决定高亮是否可见） */
  '.dshWmBtn.is-on,.dshWmBtn[aria-pressed="true"],.dshWmBtn.is-ghost.is-on{',
  '  background:color-mix(in srgb,var(--dsw-alias-brand-primary) 14%,transparent);',
  '  border-color:var(--dsw-alias-brand-primary);',
  '  color:var(--dsw-alias-label-primary);',
  '}',

  '.dshWmBody{flex:1;display:flex;min-height:0;}',
  '.dshWmSide{',
  '  width:248px;flex:none;display:flex;flex-direction:column;min-height:0;',
  '  border-right:1px solid var(--dsw-alias-border-l2);',
  '  background:var(--dsw-alias-bg-layer-1);',
  '}',
  '.dshWmSide.is-ai{width:clamp(360px,34vw,560px);border-right:none;border-left:1px solid var(--dsw-alias-border-l2);}',
  '.dshWmCompanion{display:flex;flex-direction:column;flex:1;min-height:0;padding:0 16px 16px;gap:12px;}',
  '.dshWmConversationHead{display:flex;align-items:center;justify-content:space-between;gap:8px;font-size:var(--wm-text-sm);color:var(--wm-text-dim);}.dshWmConversationHead>span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;}',
  /* 会话头降噪（2026-10-09）：作品名是唯一锚点（正文色+中黑），备忘/会话设置两个
     次级动作收成 xs 灰字——不再三个元素同量级同时抢眼。 */
  '.dshWmConversationHead>span:first-child{font-weight:var(--wm-weight-medium);color:var(--dsw-alias-label-primary);}',
  '.dshWmConversationHead .dshWmQuiet{font-size:var(--wm-text-xs);color:var(--wm-text-dim);padding:3px 2px;}',
  '.dshWmQuiet{border:0;background:transparent;color:var(--dsw-alias-label-secondary);font:inherit;font-size:var(--wm-text-sm);padding:5px 2px;cursor:pointer;white-space:nowrap;}.dshWmQuiet:hover{color:var(--dsw-alias-label-primary);}.dshWmQuiet:disabled{opacity:.4;cursor:default;}',
  '.dshWmConversation{flex:1;min-height:0;overflow:auto;overscroll-behavior:contain;padding:8px 2px;scrollbar-width:thin;}',
  '.dshWmCompanionEmpty{padding:clamp(30px,12vh,130px) 16px 30px;color:var(--dsw-alias-label-secondary);line-height:1.9;white-space:pre-line;}.dshWmCompanionEmpty h3{font-size:var(--wm-text-xl);font-weight:500;margin:16px 0 8px;color:var(--dsw-alias-label-primary);}.dshWmCompanionEmpty p{font-size:var(--wm-text-sm);margin:0;}.dshWmCompanionMark{font-size:var(--wm-text-xl);opacity:.6;}',
  '.dshWmMessage{margin:0 0 26px;}.dshWmMessageWho{display:block;font-size:var(--wm-text-xs);color:var(--wm-text-dim);margin-bottom:8px;}.dshWmMessageText{font-size:var(--wm-text-md);line-height:1.9;white-space:pre-wrap;overflow-wrap:anywhere;user-select:text;}.dshWmMessage.is-user{padding:12px 14px;border-radius:var(--wm-radius-m);background:var(--dsw-alias-bg-layer-2);}.dshWmMessage.is-error{color:var(--wm-err);}',
  '.dshWmMarkdown{white-space:normal;min-width:0;}.dshWmMarkdown>:first-child{margin-top:0;}.dshWmMarkdown>:last-child{margin-bottom:0;}',
  '.dshWmMarkdown p{margin:0 0 .85em;white-space:pre-wrap;}.dshWmMarkdown h1,.dshWmMarkdown h2,.dshWmMarkdown h3,.dshWmMarkdown h4,.dshWmMarkdown h5,.dshWmMarkdown h6{font-size:1.08em;line-height:1.6;margin:1.3em 0 .55em;font-weight:var(--wm-weight-medium);}',
  '.dshWmMarkdown ul,.dshWmMarkdown ol{padding-left:1.5em;margin:.6em 0 1em;}.dshWmMarkdown li{margin:.3em 0;}.dshWmMarkdown li>p{margin:.3em 0;}.dshWmMarkdown blockquote{margin:.8em 0;padding:.15em 0 .15em 1em;border-left:2px solid var(--dsw-alias-border-l2);color:var(--dsw-alias-label-secondary);}',
  '.dshWmMarkdown a{color:inherit;text-decoration:underline;text-underline-offset:3px;overflow-wrap:anywhere;}.dshWmMarkdown a:focus-visible,.dshWmMarkdownTable:focus-visible{outline:2px solid currentColor;outline-offset:3px;}',
  '.dshWmMarkdown code{font-size:.9em;font-family:ui-monospace,Consolas,monospace;background:var(--dsw-alias-bg-layer-2);border-radius:var(--wm-radius-s);padding:.1em .3em;}.dshWmMarkdown pre{max-width:100%;overflow:auto;white-space:pre;tab-size:2;padding:12px;border-radius:var(--wm-radius-m);background:var(--dsw-alias-bg-layer-2);line-height:1.6;}.dshWmMarkdown pre code{padding:0;background:none;}',
  '.dshWmMarkdownTable{max-width:100%;overflow:auto;margin:.8em 0;}.dshWmMarkdown table{border-collapse:collapse;font-size:.92em;min-width:100%;}.dshWmMarkdown th,.dshWmMarkdown td{padding:6px 10px;border:1px solid var(--dsw-alias-border-l2);text-align:left;vertical-align:top;}.dshWmMarkdown hr{border:0;border-top:1px solid var(--dsw-alias-border-l2);margin:1.2em 0;}',
  '.dshWmActivity{font-size:var(--wm-text-sm);color:var(--dsw-alias-label-secondary);margin:8px 0;overflow-wrap:anywhere;}.dshWmActivity pre,.dshWmReference pre{white-space:pre-wrap;overflow-wrap:anywhere;max-height:180px;overflow:auto;font-family:inherit;font-size:var(--wm-text-sm);line-height:1.6;}.dshWmActivity summary,.dshWmReference summary{cursor:pointer;}',
  '.dshWmRequest{padding:12px;border:1px solid var(--dsw-alias-border-l2);border-radius:var(--wm-radius-m);font-size:var(--wm-text-sm);display:flex;flex-direction:column;align-items:flex-start;gap:6px;margin:12px 0;}.dshWmThinking{font-size:var(--wm-text-sm);color:var(--dsw-alias-label-secondary);padding:10px 0;}',
  '.dshWmCompanionError{padding:10px;font-size:var(--wm-text-sm);line-height:1.6;color:var(--wm-err);overflow-wrap:anywhere;max-height:120px;overflow:auto;}',
  /* 内核能力缺口：常驻状态条，不是主角——密度压低、红色收进左侧竖条与标题，
     正文保持 muted（空态欢迎语才是右栏开场白）。受限=一行 Quiet 灰字。 */
  '.dshWmCapability{flex:none;display:flex;flex-direction:column;gap:2px;padding:6px 8px;border-radius:var(--wm-radius-s);font-size:var(--wm-text-sm);line-height:1.55;overflow-wrap:anywhere;border:1px solid var(--dsw-alias-border-l2);background:var(--dsw-alias-bg-layer-1);color:var(--dsw-alias-label-secondary);}',
  '.dshWmCapability.is-blocked{border-left:3px solid var(--wm-err);color:var(--dsw-alias-label-secondary);}',
  '.dshWmCapability.is-blocked strong{color:var(--wm-err);}',
  '.dshWmCapability strong{font-size:inherit;font-weight:var(--wm-weight-medium);}',
  '.dshWmCapabilityNote{opacity:.8;}',
  '.dshWmMemory{border-bottom:1px solid var(--dsw-alias-border-l2);max-height:220px;display:flex;flex-direction:column;}',
  '.dshWmMemoryList{overflow:auto;flex:1;padding:0 10px 8px;}',
  '.dshWmMemoryItem{padding:6px 8px;margin-bottom:6px;border-radius:var(--wm-radius-m);background:var(--dsw-alias-bg-layer-2);border:1px solid var(--dsw-alias-border-l2);font-size:var(--wm-text-sm);}',
  '.dshWmMemoryItem.is-retracted{opacity:.55;}',
  '.dshWmMemoryItem.is-resolved{opacity:.75;}',
  '.dshWmMemoryMeta{display:flex;gap:6px;margin-bottom:2px;font-size:var(--wm-text-xs);color:var(--wm-text-dim);}',
  '.dshWmMemoryKind{font-weight:var(--wm-weight-bold);color:var(--dsw-alias-label-secondary);}',
  '.dshWmMemoryText{line-height:1.45;color:var(--dsw-alias-label-primary);}',
  '.dshWmMemoryActions{display:flex;gap:6px;margin-top:4px;}',
  // P3：备忘完整操作（候选/编辑/历史/审计）与当轮参考面板
  '.dshWmMemoryCompose{flex-shrink:0;}',
  '.dshWmMemoryKind{background:transparent;border:1px solid var(--dsw-alias-border-l2);border-radius:var(--wm-radius-s);color:var(--dsw-alias-label-secondary);font-size:var(--wm-text-xs);padding:2px 4px;}',
  '.dshWmMemorySource{color:var(--wm-text-dim);}',
  '.dshWmMemoryNote{font-size:var(--wm-text-xs);line-height:1.5;color:var(--wm-text-dim);padding:2px 10px 4px;}',
  '.dshWmMemoryEdit{display:flex;align-items:center;gap:6px;}',
  '.dshWmMemoryHistory{margin-top:6px;border-top:1px dashed var(--dsw-alias-border-l2);padding-top:6px;}',
  '.dshWmMemoryHistoryRow{margin-bottom:6px;}.dshWmMemoryHistoryRow:last-child{margin-bottom:0;}',
  '.dshWmMemoryDiff{font-size:var(--wm-text-xs);line-height:1.5;}.dshWmMemoryDiff .is-del{color:var(--wm-err);}.dshWmMemoryDiff .is-add{color:var(--wm-ok);}',
  '.dshWmMemoryWorkspace{flex:0 1 auto;min-height:0;max-height:45vh;overflow:auto;overscroll-behavior:contain;}',
  '.dshWmMemoryWorkspace .dshWmMemory{max-height:180px;}',
  '.dshWmWorldPanel{border-bottom:1px solid var(--dsw-alias-border-l2);padding:8px 10px 12px;display:flex;flex-direction:column;gap:6px;font-size:var(--wm-text-sm);min-height:120px;flex-shrink:0;overscroll-behavior:contain;}',
  '.dshWmWorldPanel pre{white-space:pre-wrap;overflow-wrap:anywhere;max-height:180px;overflow:auto;margin:6px 0;}',
  '.dshWmWorldPanel button{margin:3px 4px 3px 0;white-space:normal;}',
  '.dshWmWorldHead{display:flex;align-items:center;gap:8px;font-weight:var(--wm-weight-medium);color:var(--dsw-alias-label-primary);}',
  '.dshWmWorldSub{font-weight:var(--wm-weight-normal);font-size:var(--wm-text-xs);color:var(--wm-text-dim);}',
  '.dshWmWorldScope{max-height:96px;overflow:auto;display:flex;flex-direction:column;gap:4px;}',
  '.dshWmWorldMsg{font-size:var(--wm-text-xs);line-height:1.4;color:var(--dsw-alias-label-secondary);background:var(--dsw-alias-bg-layer-2);border:1px solid var(--dsw-alias-border-l2);border-radius:var(--wm-radius-s);padding:4px 6px;}',
  '.dshWmWorldPanel input,.dshWmWorldPanel textarea{width:100%;box-sizing:border-box;border:1px solid var(--dsw-alias-border-l2);border-radius:var(--wm-radius-s);background:var(--dsw-alias-bg-layer-1);color:var(--dsw-alias-label-primary);font:inherit;font-size:var(--wm-text-sm);padding:4px 6px;}',
  '.dshWmWorldPanel label{font-size:var(--wm-text-xs);color:var(--wm-text-dim);margin-top:4px;}',
  '.dshWmWorldCard{border:1px solid var(--dsw-alias-border-l2);border-radius:var(--wm-radius-m);padding:8px;background:var(--dsw-alias-bg-layer-2);display:flex;flex-direction:column;gap:4px;}',
  '.dshWmWorldCardTitle{font-weight:var(--wm-weight-medium);}',
  '.dshWmWorldOps{display:flex;gap:6px;flex-wrap:wrap;margin-top:4px;}',
  '.dshWmWorldNotice{font-size:var(--wm-text-xs);color:var(--dsw-alias-label-secondary);line-height:1.5;}',
  '.dshWmWorldSrc{font-size:var(--wm-text-xs);color:var(--wm-text-dim);}',
  '.dshWmWorldRaw{max-height:120px;overflow:auto;white-space:pre-wrap;font-size:var(--wm-text-xs);border:1px dashed var(--dsw-alias-border-l2);border-radius:var(--wm-radius-s);padding:6px;}',
  '.dshWmWorldList{max-height:140px;overflow:auto;}',
  '.dshWmWorldItem{padding:4px 6px;border-radius:var(--wm-radius-s);margin-bottom:4px;background:var(--dsw-alias-bg-layer-2);border:1px solid var(--dsw-alias-border-l2);}',
  '.dshWmWorldItem.proposed{opacity:.85;}',
  '.dshWmWorldItem.retracted{opacity:.5;}',
  '.dshWmMessage.is-world-selected{outline:1px dashed var(--dsw-alias-label-tertiary);outline-offset:2px;}',
  '.dshWmMessageAction.is-on{color:var(--wm-ok);}',
  '.dshWmMessageAction{margin-top:4px;font-size:var(--wm-text-xs);}',
  '.dshWmDraftCandidates{display:flex;flex-direction:column;gap:4px;border-bottom:1px dashed var(--dsw-alias-border-l2);padding-bottom:8px;margin-bottom:8px;}',
  '.dshWmDraftCandidate{display:flex;align-items:center;gap:6px;flex-wrap:wrap;}',
  '.dshWmDraftPreview pre{white-space:pre-wrap;overflow-wrap:anywhere;max-height:160px;overflow:auto;font-family:inherit;font-size:var(--wm-text-sm);line-height:1.6;border:1px solid var(--dsw-alias-border-l2);border-radius:var(--wm-radius-m);padding:6px 8px;background:var(--dsw-alias-bg-layer-2);}',
  '.dshWmContext{display:flex;flex-direction:column;gap:4px;padding:6px 0 2px;}',
  '.dshWmContextSwitch{margin-left:auto;display:flex;align-items:center;gap:4px;font-size:var(--wm-text-xs);color:var(--wm-text-dim);}',
  '.dshWmContextPanel{max-height:200px;overflow:auto;border:1px solid var(--dsw-alias-border-l2);border-radius:var(--wm-radius-m);padding:6px 8px;background:var(--dsw-alias-bg-layer-2);}',
  '.dshWmContextItem{display:flex;align-items:flex-start;gap:6px;font-size:var(--wm-text-xs);line-height:1.5;padding:3px 0;}',
  '.dshWmContextText{color:var(--dsw-alias-label-primary);overflow-wrap:anywhere;}',
  '.dshWmContextState{margin-left:auto;font-size:var(--wm-text-xs);color:var(--wm-text-dim);white-space:nowrap;}',
  '.dshWmContextQuestions{margin-top:4px;border-top:1px dashed var(--dsw-alias-border-l2);padding-top:4px;}',
  '.dshWmCompose{border:1px solid var(--dsw-alias-border-l2);border-radius:var(--wm-radius-l);background:var(--dsw-alias-bg-layer-1);padding:12px;}.dshWmCompose:focus-within{border-color:var(--dsw-alias-label-tertiary);}.dshWmChatInput{display:block;box-sizing:border-box;width:100%;min-height:88px;max-height:200px;resize:vertical;border:0;outline:none;background:transparent;color:var(--dsw-alias-label-primary);font-family:inherit;font-size:var(--wm-text-md);line-height:1.7;}.dshWmChatInput::placeholder{color:var(--wm-text-dim);}',
  '.dshWmComposeFoot{display:flex;align-items:center;gap:8px;margin-top:8px;}.dshWmInputHint{margin-left:auto;font-size:var(--wm-text-xs);color:var(--wm-text-dim);}.dshWmSend{margin-left:auto;flex-shrink:0;width:30px;height:30px;border:0;border-radius:var(--wm-radius-m);background:var(--dsw-alias-label-primary);color:var(--dsw-alias-bg-base);font-size:var(--wm-text-xl);cursor:pointer;}.dshWmSend:disabled{opacity:.25;cursor:default;}',
  '.dshWmReference{display:flex;align-items:start;gap:8px;border-bottom:1px solid var(--dsw-alias-border-l2);padding-bottom:10px;margin-bottom:10px;font-size:var(--wm-text-sm);color:var(--dsw-alias-label-secondary);}.dshWmReference details{flex:1;min-width:0;}',
  /* G2 右栏 tab 行与左栏头同高对齐（tab 自身用 align-self:stretch + flex 居中，不靠 padding 撑） */
  '.dshWmSide.is-ai>.dshWmSideHead{display:flex;align-items:center;gap:22px;height:40px;padding:0 18px;box-sizing:border-box;}.dshWmTab{font:inherit;font-size:var(--wm-text-sm);display:inline-flex;align-items:center;height:100%;padding:0 0 2px;background:none;border:0;border-bottom:2px solid transparent;color:var(--wm-text-dim);cursor:pointer;}.dshWmTab.is-on{color:var(--dsw-alias-label-primary);border-bottom-color:var(--dsw-alias-label-primary);}',
  '@media(max-width:1250px){.dshWmInputHint{display:none;}}',

  /* G2 三处面板头统一 40px 高（左栏头 / 中栏路径行 / 右栏 tab 行），文字在同一水平带 */
  '.dshWmSideHead{',
  '  display:flex;align-items:center;gap:6px;height:40px;padding:0 12px;box-sizing:border-box;flex:none;',
  '  font-size:var(--wm-text-xs);font-weight:var(--wm-weight-medium);letter-spacing:.04em;color:var(--wm-text-dim);',
  '}',
  /* F1 「添加库 / 打开项目」内联条从顶栏搬进左栏（JSX 一字未改，仍带 .dshWmBarGroup）：
     侧栏只有 248px，顶栏那套横排会溢出，这里按上下文改成竖排撑满。 */
  '.dshWmSide .dshWmBarGroup{flex-direction:column;align-items:stretch;gap:var(--wm-space-2);padding:0 10px 10px;}',
  '.dshWmSide .dshWmBarGroup .dshWmSearch{width:100%;margin:0;}',
  '.dshWmList{flex:1;overflow:auto;padding:4px 10px 20px;}',
  '.dshWmProj{margin-bottom:18px;}',
  /* 左栏层级（2026-10-09 定结构，2026-10-10 定视觉比重）：主=章节正文（14px 正文色，
     唯一大号字）；次=项目名（14px 中黑锚点，靠字重不靠字号压过章节）；再次=分组文件夹
     （11px 灰标签，全部降权——粗体大写在中文界面只剩吵）；三级=成书/添加资料
     （xs 灰字弱钮，不与内容抢读；档案入口已挪顶栏图标，随当前文稿所属项目）。
     缩进仍表达归属，比重表达主次。 */
  '.dshWmProj>.dshWmProjOps{margin-left:18px;}',
  '.dshWmProj>.dshWmItem{margin-left:18px;width:calc(100% - 18px);font-size:var(--wm-text-md);padding:6px 8px;}',
  /* 「＋ 新章节」/「还没有章节」空态（第六轮）：与章节行同缩进、xs 灰字弱存在——是入口不是内容。 */
  '.dshWmProj>.dshWmNewChapter{margin-left:18px;display:block;width:calc(100% - 18px);text-align:left;border:0;background:transparent;color:var(--wm-text-dim);font:inherit;font-size:var(--wm-text-xs);padding:4px 8px;cursor:pointer;border-radius:var(--wm-radius-s);box-sizing:border-box;}',
  '.dshWmProj>.dshWmNewChapter:hover{color:var(--dsw-alias-brand-primary);background:var(--dsw-alias-interactive-bg-hover);}',
  '.dshWmProj>.dshWmEmptyChapters{margin-left:18px;display:flex;align-items:center;gap:8px;padding:2px 8px;font-size:var(--wm-text-xs);color:var(--wm-text-dim);}',
  '.dshWmEmptyChapters button{border:1px dashed var(--dsw-alias-border-l2);border-radius:var(--wm-radius-s);background:transparent;color:var(--dsw-alias-label-secondary);font:inherit;font-size:var(--wm-text-xs);padding:2px 10px;cursor:pointer;}',
  '.dshWmEmptyChapters button:hover{color:var(--dsw-alias-brand-primary);border-color:var(--dsw-alias-brand-primary);}',
  '.dshWmProj>details{margin-left:9px;padding-left:9px;border-left:1px solid var(--dsw-alias-border-l2);}',
  '.dshWmProj>details>summary.dshWmFolder{padding-left:2px;}',
  '.dshWmProjToggle{',
  '  display:flex;align-items:center;gap:6px;width:100%;',
  '  padding:10px 8px 6px;border:none;background:transparent;cursor:pointer;',
  '  font:inherit;font-size:var(--wm-text-md);font-weight:var(--wm-weight-medium);color:var(--dsw-alias-label-primary);',
  '  text-align:left;',
  '}',
  '.dshWmProjToggle:hover{color:var(--dsw-alias-brand-primary);}',
  /* 散稿桶（isLoose）：不是一部作品，只是库根散稿的收容——降到灰字小级、
     默认收起（LibraryPane 控制）、排序沉底（store 控制），不与作品名平级（2026-10-10）。 */
  '.dshWmProj.is-loose{margin-bottom:6px;}',
  '.dshWmProj.is-loose>.dshWmProjToggle{font-size:var(--wm-text-xs);color:var(--wm-text-dim);padding-top:6px;}',
  '.dshWmProjChev{font-size:var(--wm-text-xs);color:var(--wm-text-dim);transition:transform .12s;flex:none;}',
  '.dshWmProjChev.is-open{transform:rotate(90deg);}',
  '.dshWmFolder{',
  '  font-size:var(--wm-text-xs);font-weight:var(--wm-weight-medium);letter-spacing:.05em;',
  '  color:var(--wm-text-dim);padding:8px 8px 3px;',
  '}',
  '.dshWmSearch{',
  '  width:100%;margin:0 0 8px;padding:7px 10px;border-radius:var(--wm-radius-m);',
  '  border:1px solid var(--dsw-alias-border-l2);',
  '  background:var(--dsw-alias-bg-layer-2);color:var(--dsw-alias-label-primary);',
  '  font:inherit;font-size:var(--wm-text-sm);outline:none;box-sizing:border-box;',
  '}',
  '.dshWmSearch:focus{border-color:var(--dsw-alias-brand-primary);}',
  '.dshWmItem{',
  /* G1 行高收紧：一屏 6 → 约 10 个文件（两行制保留：标题 + 字数） */
  '  display:block;width:100%;text-align:left;cursor:pointer;',
  '  padding:var(--wm-space-1) var(--wm-space-2);margin-bottom:2px;border-radius:var(--wm-radius-m);border:1px solid transparent;',
  '  background:transparent;color:var(--dsw-alias-label-primary);',
  '  font:inherit;font-size:var(--wm-text-sm);line-height:1.25;box-sizing:border-box;',
  '  transition:background .12s ease,border-color .12s ease;',
  '}',
  '.dshWmItem:hover{background:var(--dsw-alias-interactive-bg-hover);}',
  '.dshWmItem.is-on{',
  '  border-color:color-mix(in srgb,var(--dsw-alias-brand-primary) 50%,transparent);',
  '  background:color-mix(in srgb,var(--dsw-alias-brand-primary) 12%,transparent);',
  '}',
  '.dshWmItemRow{display:flex;align-items:baseline;gap:var(--wm-space-1);}',
  '.dshWmItemTitle{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;flex:1;min-width:0;}',
  '.dshWmItemMeta{display:block;font-size:var(--wm-text-xs);color:var(--wm-text-dim);margin-top:1px;line-height:1.25;}',
  /* G1 版本徽标：当前版走 ok 色系（实边 + 底），历史版只留一圈弱边 + dim 字——
     选中行底色是 brand 12%，品牌色徽标会糊在一起，所以当前版不再用 brand。 */
  '.dshWmVer{',
  '  display:inline-block;margin-left:var(--wm-space-1);padding:0 5px;border-radius:var(--wm-radius-s);flex:none;',
  '  font-size:var(--wm-text-xs);font-weight:var(--wm-weight-bold);line-height:15px;',
  '  background:color-mix(in srgb,var(--wm-ok) 22%,transparent);',
  '  border:1px solid color-mix(in srgb,var(--wm-ok) 50%,transparent);',
  '  color:var(--wm-ok);',
  '}',
  '.dshWmVer.is-hist{background:transparent;color:var(--wm-text-dim);border-color:var(--dsw-alias-border-l2);}',

  '.dshWmMain{flex:1;display:flex;flex-direction:column;min-width:0;min-height:0;position:relative;}',
  /* G2 中栏：去掉头部 24px 上边距，让路径行与左右栏头同处 52–92px 那条带（行可能换行，用 min-height 不裁切） */
  '.dshWmDocChrome{flex:none;padding:0 32px;max-width:820px;margin:0 auto;width:100%;box-sizing:border-box;}',
  '.dshWmPathRow{display:flex;align-items:center;gap:8px;min-height:40px;box-sizing:border-box;font-size:var(--wm-text-xs);color:var(--wm-text-dim);flex-wrap:wrap;}',
  '.dshWmPathText{flex:1;min-width:120px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;}',
  '.dshWmDocName{margin:10px 0 4px;font-size:var(--wm-text-xl);font-weight:650;line-height:1.3;}',
  '.dshWmDocRule{height:1px;margin:12px 0 0;background:var(--dsw-alias-border-l2);}',
  '.dshWmHistBanner{',
  '  display:flex;align-items:center;gap:10px;margin-top:10px;padding:8px 12px;',
  '  border-radius:var(--wm-radius-m);border:1px solid var(--dsw-alias-border-l2);',
  '  background:color-mix(in srgb,var(--wm-warn) 12%,transparent);',
  '  font-size:var(--wm-text-sm);',
  '}',
  '.dshWmVerBar{display:flex;flex-wrap:wrap;gap:6px;align-items:center;margin-top:10px;}',
  '.dshWmVerBarLabel{font-size:var(--wm-text-xs);font-weight:var(--wm-weight-bold);letter-spacing:.06em;color:var(--wm-text-dim);}',
  '.dshWmVerChip{',
  '  font:inherit;font-size:var(--wm-text-xs);padding:3px 8px;border-radius:999px;cursor:pointer;',
  '  border:1px solid var(--dsw-alias-border-l2);background:transparent;',
  '  color:var(--dsw-alias-label-secondary);',
  '}',
  '.dshWmVerMore{align-self:center;color:var(--wm-text-dim);font-size:var(--wm-text-xs);padding:0 2px;}',
  '.dshWmVerChip:hover{border-color:var(--dsw-alias-brand-primary);}',
  '.dshWmVerChip.is-on{',
  '  border-color:var(--dsw-alias-brand-primary);',
  '  background:color-mix(in srgb,var(--dsw-alias-brand-primary) 16%,transparent);',
  '  color:var(--dsw-alias-label-primary);font-weight:var(--wm-weight-medium);',
  '}',
  '.dshWmEditorWrap{flex:1;min-height:0;display:flex;justify-content:center;}',
  '.dshWmEditor{',
  '  flex:1;min-height:0;max-width:820px;width:100%;',
  '  resize:none;outline:none;border:none;box-sizing:border-box;',
  '  padding:20px 32px 48px;',
  '  font-family:"Source Han Serif SC","Noto Serif SC","Songti SC","SimSun",Georgia,serif;',
  '  font-size:var(--dsh-wm-font-size,17px);',
  '  line-height:var(--dsh-wm-line-height,1.95);letter-spacing:.02em;',
  '  color:var(--dsw-alias-label-primary);background:transparent;',
  '}',
  '.dshWmStatus{',
  '  flex:none;height:32px;display:flex;align-items:center;gap:10px;padding:0 16px;',
  '  border-top:1px solid var(--dsw-alias-border-l2);',
  '  background:var(--dsw-alias-bg-layer-1);',
  '  font-size:var(--wm-text-xs);color:var(--wm-text-dim);',
  '}',
  '.dshWmStatus .dot{width:6px;height:6px;border-radius:50%;background:var(--dsw-alias-label-tertiary);}',
  '.dshWmStatus .dot.is-dirty{background:var(--wm-warn);}',
  '.dshWmStatus .dot.is-saved{background:var(--wm-ok);}',
  '.dshWmStatusSep{opacity:.35;}',
  '.dshWmStatus .dot.is-error{background:var(--wm-err);}',
  '.dshWmStatusError{color:var(--wm-err);font-weight:var(--wm-weight-medium);}',
  /* 保存/读取失败的常驻行：压在状态条上方，带得出路的按钮（重试、另存新版） */
  '.dshWmDocAlert{flex:none;display:flex;align-items:center;gap:8px;padding:8px 16px;font-size:var(--wm-text-sm);line-height:1.6;color:var(--wm-err);background:color-mix(in srgb,var(--wm-err) 8%,transparent);border-top:1px solid var(--dsw-alias-border-l2);overflow-wrap:anywhere;}',
  '.dshWmDocAlert>span:first-child{min-width:0;}',
  '.dshWmDocAlert .dshWmBtn{flex:none;}',

  /* 编辑器查找/替换栏：压在版本条与稿面之间 */
  '.dshWmFindBar{flex:none;display:flex;align-items:center;gap:6px;padding:6px 16px;border-top:1px solid var(--dsw-alias-border-l2);background:var(--dsw-alias-bg-layer-1);flex-wrap:wrap;}',
  '.dshWmFindInput{flex:0 1 180px;min-width:110px;height:26px;padding:0 8px;font-size:var(--wm-text-sm);color:var(--dsw-alias-label-primary);background:var(--dsw-alias-bg-layer-2);border:1px solid var(--dsw-alias-border-l2);border-radius:var(--wm-radius-s);outline:none;}',
  '.dshWmFindInput.is-replace{flex:0 1 160px;}',
  '.dshWmFindInput:focus{border-color:var(--dsw-alias-border-l3,var(--dsw-alias-border-l2));}',
  '.dshWmFindCount{font-size:var(--wm-text-xs);color:var(--wm-text-dim);min-width:44px;text-align:center;}',
  '.dshWmFindHint{font-size:var(--wm-text-xs);color:var(--wm-text-dim);opacity:.7;margin-left:auto;white-space:nowrap;}',
  '.dshWmFindBar .dshWmBtn{flex:none;}',

  /* 状态条里的今日码字芯片：与字数/格式同属「元信息」，让位给检查摘要 */
  '.dshWmStatus [data-wm-stats-today]{color:var(--wm-text-dim);font-variant-numeric:tabular-nums;}',

  '.dshWmAiBody{',
  '  flex:1;display:flex;flex-direction:column;min-height:0;',
  '  padding:8px 12px 20px;gap:8px;overflow:auto;',
  '}',
  '.dshWmAiSection{display:flex;flex-direction:column;gap:8px;}',
  '.dshWmAiSectionTitle{font-size:var(--wm-text-sm);font-weight:var(--wm-weight-bold);letter-spacing:.08em;text-transform:uppercase;color:var(--dsw-alias-label-secondary);}',
  '.dshWmAiMain{flex:1;min-height:0;display:flex;flex-direction:column;gap:8px;}',
  '.dshWmAiActions{display:flex;flex-wrap:wrap;gap:6px;}',
  '.dshWmAiOut{',
  '  flex:1;min-height:140px;overflow:auto;padding:12px;border-radius:var(--wm-radius-m);',
  '  border:1px solid var(--dsw-alias-border-l2);',
  '  background:var(--dsw-alias-bg-layer-2);',
  '  font-size:var(--wm-text-sm);line-height:1.7;white-space:pre-wrap;word-break:break-word;',
  '}',
  '.dshWmAiHint{font-size:var(--wm-text-xs);color:var(--wm-text-dim);line-height:1.5;}',
  /* 非错误但作者必须知道的提示（如"只处理了前 N 字"）：2026-10-10 */
  '.dshWmAiNote{font-size:var(--wm-text-xs);color:var(--wm-warn);line-height:1.5;}',
  '.dshWmSec{display:flex;flex-direction:column;gap:6px;}',
  '.dshWmSecToggle{',
  '  display:flex;align-items:center;gap:6px;width:100%;',
  '  padding:6px 0;border:none;background:transparent;cursor:pointer;',
  '  font:inherit;font-size:var(--wm-text-xs);font-weight:var(--wm-weight-bold);letter-spacing:.06em;',
  '  text-transform:uppercase;color:var(--wm-text-dim);text-align:left;',
  '}',
  '.dshWmSecToggle:hover{color:var(--dsw-alias-label-primary);}',
  '.dshWmSecBadge{',
  '  margin-left:auto;font-size:var(--wm-text-xs);font-weight:var(--wm-weight-medium);letter-spacing:0;text-transform:none;',
  '  padding:1px 6px;border-radius:999px;',
  '  background:var(--dsw-alias-bg-layer-2);color:var(--dsw-alias-label-secondary);',
  '}',
  '.dshWmSecBadge.is-pass{color:var(--wm-ok);}',
  '.dshWmSecBadge.is-fail{color:var(--wm-err);}',
  '.dshWmGateList{display:flex;flex-direction:column;gap:3px;}',
  '.dshWmGateRow{',
  '  display:flex;gap:8px;align-items:baseline;font-size:var(--wm-text-sm);line-height:1.45;',
  '  padding:5px 8px;border-radius:var(--wm-radius-m);background:var(--dsw-alias-bg-layer-2);',
  '}',
  '.dshWmGateRow .ok{color:var(--wm-ok);font-weight:var(--wm-weight-bold);font-size:var(--wm-text-xs);flex:none;width:auto;}',
  '.dshWmGateRow .bad{color:var(--wm-err);font-weight:var(--wm-weight-bold);font-size:var(--wm-text-xs);flex:none;width:auto;}',
  '.dshWmGateLabel{color:var(--dsw-alias-label-primary);flex:none;}',
  '.dshWmGateDetail{color:var(--wm-text-dim);flex:1;word-break:break-word;font-size:var(--wm-text-xs);}',
  '.dshWmLedger{',
  '  display:flex;flex-direction:column;gap:6px;font-size:var(--wm-text-sm);line-height:1.55;',
  '  padding:8px 10px;border-radius:var(--wm-radius-m);',
  '  border:1px solid var(--dsw-alias-border-l2);background:var(--dsw-alias-bg-layer-2);',
  '  color:var(--dsw-alias-label-secondary);',
  '}',
  '.dshWmLedgerRow{display:flex;gap:8px;}',
  '.dshWmLedgerK{flex:none;min-width:4.5em;color:var(--wm-text-dim);font-size:var(--wm-text-xs);}',
  '.dshWmLedgerV{flex:1;word-break:break-word;color:var(--dsw-alias-label-primary);}',

  /* 码字统计（检查页）：今日大数 + 连击 + 近 14 天柱条 + 日更目标 */
  '.dshWmStats{display:flex;flex-direction:column;gap:8px;font-size:var(--wm-text-sm);line-height:1.55;padding:8px 10px;border-radius:var(--wm-radius-m);border:1px solid var(--dsw-alias-border-l2);background:var(--dsw-alias-bg-layer-2);color:var(--dsw-alias-label-secondary);}',
  '.dshWmStatsHead{display:flex;align-items:baseline;gap:10px;}',
  '.dshWmStatsToday{font-size:var(--wm-text-sm);color:var(--dsw-alias-label-secondary);font-variant-numeric:tabular-nums;}',
  '.dshWmStatsToday b{font-size:var(--wm-text-lg);color:var(--dsw-alias-label-primary);font-weight:var(--wm-weight-bold);}',
  '.dshWmStatsToday .is-hit{color:var(--wm-ok);}',
  '.dshWmStatsStreak{font-size:var(--wm-text-xs);color:var(--wm-warn);font-variant-numeric:tabular-nums;}',
  '.dshWmStatsBars{display:flex;align-items:flex-end;gap:3px;height:46px;padding:2px 0;}',
  '.dshWmStatsBarCol{flex:1;display:flex;align-items:flex-end;justify-content:center;height:100%;}',
  '.dshWmStatsBar{width:70%;min-height:1px;border-radius:var(--wm-radius-s) var(--wm-radius-s) 0 0;background:var(--dsw-alias-border-l2);}',
  '.dshWmStatsBar.is-on{background:color-mix(in srgb,var(--wm-ok) 65%,var(--dsw-alias-bg-layer-1));}',
  '.dshWmStatsBar.is-today{outline:1px solid var(--dsw-alias-border-l3,var(--dsw-alias-border-l2));outline-offset:1px;}',
  '.dshWmGoalRow{display:flex;align-items:center;gap:6px;}',
  '.dshWmGoalInput{flex:0 1 90px;min-width:56px;height:24px;padding:0 8px;font-size:var(--wm-text-sm);color:var(--dsw-alias-label-primary);background:var(--dsw-alias-bg-layer-1);border:1px solid var(--dsw-alias-border-l2);border-radius:var(--wm-radius-s);outline:none;font-variant-numeric:tabular-nums;}',
  '.dshWmGoalUnit{font-size:var(--wm-text-xs);color:var(--wm-text-dim);}',
  '.dshWmGoalRow .dshWmBtn{flex:none;margin-left:auto;}',

  /* 改稿预览（选区改稿 diff 回路）：与版本 diff 同骨架，加一条建议色左边线区分 */
  '.dshWmRewrite{border-left:3px solid color-mix(in srgb,var(--dsw-alias-brand-primary) 55%,transparent);}',
  '.dshWmRewrite .dshWmBtn{flex:none;}',

  /* 伙伴回复里的 [[文稿名]] 跳转 chip */
  '.dshWmJumpRef{display:inline-block;margin:0 2px;padding:0 8px;height:22px;line-height:20px;font-size:var(--wm-text-sm);border-radius:999px;border:1px solid color-mix(in srgb,var(--dsw-alias-brand-primary) 45%,transparent);background:color-mix(in srgb,var(--dsw-alias-brand-primary) 8%,transparent);color:var(--dsw-alias-brand-primary);cursor:pointer;}',
  '.dshWmJumpRef:hover{background:color-mix(in srgb,var(--dsw-alias-brand-primary) 16%,transparent);}',

  /* 参考预览行的「正文提及」徽标 */
  '.dshWmMention{flex:none;padding:0 6px;border-radius:999px;font-size:var(--wm-text-xs);line-height:18px;color:var(--dsw-alias-brand-primary);border:1px solid color-mix(in srgb,var(--dsw-alias-brand-primary) 40%,transparent);}',

  /* 大纲视图（只读投影） */
  '.dshWmOutline{padding:4px 8px 16px;display:flex;flex-direction:column;gap:10px;}',
  '.dshWmOutlineProj{display:flex;flex-direction:column;gap:4px;}',
  '.dshWmOutlineTitle{font-size:var(--wm-text-sm);font-weight:var(--wm-weight-bold);color:var(--dsw-alias-label-secondary);padding:4px 2px;}',
  '.dshWmOutlineStructure{font-size:var(--wm-text-xs);color:var(--wm-text-dim);padding:2px 4px;}',
  '.dshWmOutlineStructure summary{cursor:pointer;}',
  '.dshWmOutlineStructLine{padding:1px 0 1px 14px;}',
  '.dshWmOutlineRow{display:flex;align-items:baseline;gap:8px;padding:6px 8px;border-radius:var(--wm-radius-m);border:1px solid var(--dsw-alias-border-l2);background:var(--dsw-alias-bg-layer-2);flex-wrap:wrap;}',
  '.dshWmOutlineName{flex:none;max-width:100%;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;text-align:left;font-size:var(--wm-text-sm);color:var(--dsw-alias-label-primary);background:none;border:none;cursor:pointer;padding:0;}',
  '.dshWmOutlineName:hover{text-decoration:underline;}',
  '.dshWmOutlineChars{flex:none;font-size:var(--wm-text-xs);color:var(--wm-text-dim);font-variant-numeric:tabular-nums;}',
  '.dshWmOutlineGate{flex:none;padding:0 6px;border-radius:999px;font-size:var(--wm-text-xs);line-height:18px;font-variant-numeric:tabular-nums;}',
  '.dshWmOutlineGate.is-pass{color:var(--wm-ok);border:1px solid color-mix(in srgb,var(--wm-ok) 40%,transparent);}',
  '.dshWmOutlineGate.is-fail{color:var(--wm-err);border:1px solid color-mix(in srgb,var(--wm-err) 40%,transparent);}',
  '.dshWmOutlineHook{flex-basis:100%;font-size:var(--wm-text-xs);color:var(--wm-text-dim);overflow:hidden;text-overflow:ellipsis;white-space:nowrap;}',

  /* 卡片态（大纲视图的 corkboard）：网格卡片，可拖拽重排 */
  '.dshWmOutlineHint{font-size:var(--wm-text-xs);color:var(--wm-text-dim);opacity:.75;}',
  '.dshWmCards{display:grid;grid-template-columns:repeat(auto-fill,minmax(190px,1fr));gap:8px;}',
  '.dshWmCard{position:relative;display:flex;flex-direction:column;gap:4px;min-height:84px;padding:8px 10px;border-radius:var(--wm-radius-m);border:1px solid var(--dsw-alias-border-l2);background:var(--dsw-alias-bg-layer-2);cursor:grab;}',
  '.dshWmCard:active{cursor:grabbing;}',
  '.dshWmCardName{flex:none;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;text-align:left;font-size:var(--wm-text-sm);font-weight:var(--wm-weight-medium);color:var(--dsw-alias-label-primary);background:none;border:none;cursor:pointer;padding:0;}',
  '.dshWmCardName:hover{text-decoration:underline;}',
  '.dshWmCardDrag{position:absolute;top:6px;right:8px;font-size:var(--wm-text-xs);color:var(--wm-text-dim);letter-spacing:-1px;}',
  '.dshWmDiff{',
  '  flex:none;max-height:36%;overflow:auto;',
  '  border-top:1px solid var(--dsw-alias-border-l2);',
  '  background:var(--dsw-alias-bg-layer-1);padding:8px 12px;',
  '}',
  '.dshWmDiffHead{display:flex;align-items:center;gap:8px;margin-bottom:6px;font-size:var(--wm-text-xs);color:var(--wm-text-dim);}',
  '.dshWmDiffLine{',
  '  font-family:var(--ds-font-family-code,monospace);font-size:var(--wm-text-xs);line-height:1.55;',
  '  white-space:pre-wrap;word-break:break-word;padding:1px 6px;border-radius:var(--wm-radius-s);',
  '}',
  '.dshWmDiffLine.add{background:color-mix(in srgb,var(--wm-ok) 14%,transparent);}',
  '.dshWmDiffLine.del{background:color-mix(in srgb,var(--wm-err) 12%,transparent);text-decoration:line-through;}',
  '.dshWmDiffLine.ctx{color:var(--dsw-alias-label-tertiary);}',
  '.dshWmWelcome{',
  '  flex:1;display:flex;flex-direction:column;align-items:center;justify-content:center;',
  '  gap:14px;padding:40px;text-align:center;color:var(--dsw-alias-label-secondary);',
  '}',
  '.dshWmWelcomeTitle{font-size:var(--wm-text-xl);font-weight:650;color:var(--dsw-alias-label-primary);}',
  '.dshWmWelcomeBody{font-size:var(--wm-text-sm);line-height:1.7;max-width:420px;}',
  '.dshWmEmpty{padding:16px;color:var(--wm-text-dim);font-size:var(--wm-text-sm);line-height:1.6;}',
  /* 空页（无文件时的第一屏）：纯写作默认态的主角——一句标题 + 两个文字级动作。
     类名避开 LibraryPane 已占用的 .dshWmEmpty/.dshWmWelcome。 */
  '.dshWmEmptyPage{flex:1;min-height:0;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:var(--wm-space-4);padding:40px;text-align:center;}',
  '.dshWmEmptyTitle{font-size:var(--wm-text-xl);font-weight:var(--wm-weight-medium);letter-spacing:.06em;color:var(--dsw-alias-label-secondary,#52554b);}',
  '.dshWmEmptyActs{display:flex;align-items:center;gap:var(--wm-space-3);font-size:var(--wm-text-sm);color:var(--wm-text-dim);}',
  '.dshWmEmptyDot{opacity:.5;}',
  '.dshWmFlash{',
  '  position:absolute;left:50%;transform:translateX(-50%);top:60px;z-index:20;',
  '  max-width:70%;padding:8px 14px;border-radius:var(--wm-radius-m);',
  '  background:color-mix(in srgb,var(--dsw-alias-bg-layer-3) 95%,transparent);',
  '  border:1px solid var(--dsw-alias-border-l2);',
  '  color:var(--dsw-alias-label-primary);font-size:var(--wm-text-sm);',
  '  box-shadow:0 4px 16px rgba(0,0,0,.2);',
  '}',

  'body[data-writing-focus="1"] .dshWmSide{display:none;}',
  'body[data-writing-focus="1"] .dshWmEditor{',
  '  font-size:calc(var(--dsh-wm-font-size,17px) + 1px);',
  '  line-height:calc(var(--dsh-wm-line-height,1.95) + 0.1);max-width:720px;',
  '}',
  'body[data-writing-focus="1"] .dshWmDocChrome{max-width:720px;}',
  'html[data-writing-mode] body[data-writing-lib="0"] .dshWmSide:not(.is-ai){display:none;}',
  /* 就地收展（2026-10-09）：收起态在身体边缘留 26px 竖排 rail（点开即恢复），
     展开态由面板头里的 ⟨/⟩ 折钮收起；专注模式连 rail 一起藏。 */
  '.dshWmRail{',
  '  flex:none;width:26px;padding:14px 0;border:0;cursor:pointer;',
  '  background:var(--dsw-alias-bg-layer-1);color:var(--dsw-alias-label-tertiary);',
  '  font:inherit;font-size:var(--wm-text-xs);letter-spacing:.2em;',
  '  writing-mode:vertical-rl;text-align:center;',
  '  display:flex;align-items:center;justify-content:center;',
  '}',
  '.dshWmRail:hover{color:var(--dsw-alias-label-primary);background:var(--dsw-alias-interactive-bg-hover);}',
  '.dshWmRail.is-lib{border-right:1px solid var(--dsw-alias-border-l2);}',
  '.dshWmRail.is-ai{border-left:1px solid var(--dsw-alias-border-l2);}',
  'body[data-writing-focus="1"] .dshWmRail{display:none;}',
  '.dshWmSideFold{flex:none;width:24px;height:24px;padding:0;border:0;border-radius:var(--wm-radius-s);background:transparent;color:var(--wm-text-dim);cursor:pointer;font:inherit;font-size:var(--wm-text-md);line-height:1;display:inline-flex;align-items:center;justify-content:center;}',
  '.dshWmSideFold:hover{background:var(--dsw-alias-interactive-bg-hover);color:var(--dsw-alias-label-primary);}',

  /* 导出成书面板：覆盖中央编辑区（编辑器不卸载），项目操作行 */
  /* 操作行降权（2026-10-10）：档案/成书/添加资料是三级动作——xs 灰字、按钮去边框，
     不再与章节行同量级。 */
  '.dshWmProjOps{display:flex;align-items:center;gap:2px;margin:0 0 6px;}',
  /* 「＋ 添加资料」降权（2026-10-10 第七轮）：不再 flex:1 撑满整行——收成内容宽的弱文本触发器，
     常态透明边、hover/焦点才出虚线框；资料添齐时 LibraryPane 干脆不渲染它。 */
  '.dshWmProjOps .dshWmSearch{margin:0;flex:none;width:auto;max-width:150px;min-width:0;font-size:var(--wm-text-xs);padding:2px 4px;}',
  '.dshWmProjOps .dshWmSearch.dshWmAddRes{border-color:transparent;background:transparent;color:var(--wm-text-dim);}',
  '.dshWmProjOps .dshWmSearch.dshWmAddRes:hover,.dshWmProjOps .dshWmSearch.dshWmAddRes:focus{border-color:var(--dsw-alias-border-l2);background:transparent;color:var(--dsw-alias-label-secondary);}',
  '.dshWmProjOps .dshWmBtn{flex:none;font-size:var(--wm-text-xs);padding:3px 7px;border-color:transparent;color:var(--wm-text-dim);}',
  '.dshWmProjOps .dshWmBtn:hover{color:var(--dsw-alias-label-primary);border-color:transparent;background:var(--dsw-alias-interactive-bg-hover);}',
  '.dshWmExport{',
  '  position:absolute;inset:0;z-index:5;display:flex;flex-direction:column;min-height:0;',
  '  background:var(--dsw-alias-bg-base);',
  '}',
  '.dshWmExportScroll{flex:1;overflow:auto;padding:24px 32px 40px;}',
  '.dshWmExportInner{max-width:820px;margin:0 auto;display:flex;flex-direction:column;gap:12px;}',
  '.dshWmExportHead{display:flex;align-items:center;gap:10px;}',
  '.dshWmExportTitle{font-size:var(--wm-text-lg);font-weight:650;color:var(--dsw-alias-label-primary);}',
  '.dshWmExportField{display:flex;align-items:center;gap:10px;}',
  '.dshWmExportField .dshWmSearch{flex:1;}',
  '.dshWmExportLabel{flex:none;font-size:var(--wm-text-xs);font-weight:var(--wm-weight-medium);letter-spacing:.04em;color:var(--wm-text-dim);}',
  '.dshWmExportCheck{display:flex;align-items:baseline;gap:8px;font-size:var(--wm-text-sm);color:var(--dsw-alias-label-secondary);cursor:pointer;}',
  '.dshWmExportCheck input{flex:none;align-self:center;}',
  '.dshWmExportList{',
  '  display:flex;flex-direction:column;gap:2px;max-height:46vh;overflow:auto;',
  '  padding:6px;border-radius:var(--wm-radius-m);',
  '  border:1px solid var(--dsw-alias-border-l2);background:var(--dsw-alias-bg-layer-1);',
  '}',
  '.dshWmExportRow{',
  '  display:flex;align-items:center;gap:8px;padding:6px 8px;border-radius:var(--wm-radius-m);cursor:pointer;',
  '  font-size:var(--wm-text-sm);color:var(--dsw-alias-label-primary);',
  '}',
  '.dshWmExportRow:hover{background:var(--dsw-alias-interactive-bg-hover);}',
  '.dshWmExportRow.is-off .dshWmExportRowName{color:var(--wm-text-dim);}',
  '.dshWmExportRowName{flex:1;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;}',
  '.dshWmExportRowMeta{flex:none;font-size:var(--wm-text-xs);color:var(--wm-text-dim);}',
  '.dshWmExportFoot{display:flex;align-items:center;gap:10px;font-size:var(--wm-text-xs);color:var(--wm-text-dim);}',
  /* 会话列表区（伙伴 tab 顶部折叠区） */
  '.dshWmCompanionWrap{display:flex;flex-direction:column;flex:1;min-height:0;}',
  /* 文字工具 ✦ 图标菜单（2026-10-09 第二轮，取代同日的右栏抽屉）：输入框旁小图标，
     上弹菜单选中工具 → armed chip 压在输入框上方，Enter/发送键运行；产出区在输入框正上方。
     菜单常挂载、关闭时 display:none——与「辅助 ▾」同一模式（门禁 .click() 不看可见性）；
     菜单行可见文本逐字等于工具名，说明在 title（按文本精确点击的断言不受影响）。 */
  '.dshWmToolsAnchor{position:relative;flex:none;display:inline-flex;}',
  '.dshWmToolsBtn{width:30px;height:30px;padding:0;border:1px solid var(--dsw-alias-border-l2);border-radius:var(--wm-radius-m);background:transparent;color:var(--wm-text-dim);font:inherit;font-size:14px;line-height:1;cursor:pointer;display:inline-flex;align-items:center;justify-content:center;}',
  '.dshWmToolsBtn:hover{color:var(--dsw-alias-label-primary);border-color:var(--dsw-alias-label-tertiary);}',
  '.dshWmToolsBtn.is-on{color:var(--dsw-alias-brand-primary);border-color:var(--dsw-alias-brand-primary);}',
  '.dshWmToolsMenu:not(.is-open){display:none;}',
  '.dshWmToolsMenu{position:absolute;bottom:calc(100% + 6px);left:0;z-index:8;display:flex;flex-direction:column;min-width:132px;padding:4px;border:1px solid var(--dsw-alias-border-l2);border-radius:var(--wm-radius-m);background:var(--dsw-alias-bg-layer-3);box-shadow:0 8px 24px rgba(0,0,0,.14);}',
  '.dshWmToolsMenuRow{display:block;width:100%;padding:6px 10px;border:0;border-radius:var(--wm-radius-s);background:transparent;font:inherit;font-size:var(--wm-text-sm);color:var(--dsw-alias-label-primary);text-align:left;cursor:pointer;}',
  '.dshWmToolsMenuRow:hover{background:var(--dsw-alias-interactive-bg-hover);}',
  '.dshWmToolsMenuRow.is-on{background:var(--dsw-alias-bg-layer-2);}',
  '.dshWmToolsMenuRow:disabled{opacity:.4;cursor:default;}',
  '.dshWmToolChip{display:inline-flex;align-items:center;gap:4px;align-self:flex-start;padding:2px 4px 2px 10px;border-radius:999px;border:1px solid var(--dsw-alias-border-l2);background:var(--dsw-alias-bg-layer-2);font-size:var(--wm-text-xs);color:var(--dsw-alias-label-secondary);}',
  '.dshWmToolChipX{width:18px;height:18px;padding:0;border:0;border-radius:50%;background:transparent;color:var(--wm-text-dim);font:inherit;line-height:1;cursor:pointer;display:inline-flex;align-items:center;justify-content:center;}',
  '.dshWmToolChipX:hover{color:var(--dsw-alias-label-primary);background:var(--dsw-alias-interactive-bg-hover);}',
  '.dshWmToolOut{display:flex;flex-direction:column;gap:8px;padding-bottom:8px;border-bottom:1px solid var(--dsw-alias-border-l2);}',
  '.dshWmToolOut .dshWmAiOut{flex:none;min-height:96px;max-height:220px;}',
  '.dshWmSessList{flex:none;padding:10px 16px 0;display:flex;flex-direction:column;gap:4px;}',
  '.dshWmSessRows{display:flex;flex-direction:column;gap:2px;padding:2px 0 4px;}',
  '.dshWmSessRow{display:flex;align-items:center;gap:8px;padding:5px 8px;border-radius:var(--wm-radius-m);border:0;background:none;font:inherit;font-size:var(--wm-text-sm);color:var(--dsw-alias-label-primary);cursor:pointer;text-align:left;}',
  '.dshWmSessRow:hover{background:var(--dsw-alias-interactive-bg-hover);}',
  '.dshWmSessRow.is-on{background:var(--dsw-alias-bg-layer-2);}',
  '.dshWmSessDot{flex:none;width:14px;text-align:center;color:var(--dsw-alias-label-tertiary);}',
  '.dshWmSessDot.is-live{color:var(--dsw-alias-brand-primary);}',
  '.dshWmSessName{flex:1;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;}',
  '.dshWmSessMeta{flex:none;font-size:var(--wm-text-xs);color:var(--wm-text-dim);}',

  /* 作品档案：覆盖中央编辑区的只读汇总页（与「成书」同层级手法，z-index 高一层便于两面板互斥切换） */
  '.dshWmWiki{position:absolute;inset:0;z-index:6;display:flex;flex-direction:column;min-height:0;background:var(--dsw-alias-bg-base);}',
  '.dshWmWikiBar{flex:none;display:flex;align-items:center;gap:10px;padding:12px 24px;border-bottom:1px solid var(--dsw-alias-border-l2);}',
  '.dshWmWikiTitle{font-size:var(--wm-text-lg);font-weight:650;color:var(--dsw-alias-label-primary);}',
  '.dshWmWikiSub{font-size:var(--wm-text-xs);color:var(--wm-text-dim);}',
  '.dshWmWikiScroll{flex:1;min-height:0;overflow:auto;width:100%;max-width:960px;margin:0 auto;padding:22px 24px 48px;display:flex;flex-direction:column;gap:26px;}',
  '.dshWmWikiSection{display:flex;flex-direction:column;gap:10px;}',
  '.dshWmWikiSectionHead{display:flex;align-items:baseline;gap:8px;}',
  '.dshWmWikiSectionHead h3{margin:0;font-size:var(--wm-text-sm);font-weight:var(--wm-weight-bold);letter-spacing:.08em;text-transform:uppercase;color:var(--dsw-alias-label-secondary);}',
  '.dshWmWikiSectionMeta{font-size:var(--wm-text-xs);color:var(--wm-text-dim);}',
  '.dshWmWikiSectionError{display:flex;align-items:center;gap:8px;margin:0;font-size:var(--wm-text-sm);color:var(--wm-err);}',
  '.dshWmWikiCards{display:grid;grid-template-columns:repeat(auto-fill,minmax(260px,1fr));gap:10px;}',
  '.dshWmWikiCard{display:flex;flex-direction:column;gap:6px;padding:12px 14px;border-radius:var(--wm-radius-l);border:1px solid var(--dsw-alias-border-l2);background:var(--dsw-alias-bg-layer-1);}',
  '.dshWmWikiCard.has-boundary{border-left:3px solid var(--wm-warn);}',
  '.dshWmWikiCardHead{display:flex;align-items:baseline;gap:8px;}',
  '.dshWmWikiCardHead h4{margin:0;font-size:var(--wm-text-md);font-weight:var(--wm-weight-medium);color:var(--dsw-alias-label-primary);}',
  '.dshWmWikiCardFrom{margin-left:auto;flex:none;font-size:var(--wm-text-xs);color:var(--wm-text-dim);}',
  '.dshWmWikiConclusion{margin:0;font-size:var(--wm-text-md);line-height:1.75;color:var(--dsw-alias-label-primary);overflow-wrap:anywhere;}',
  '.dshWmWikiBoundary{margin:0;font-size:var(--wm-text-sm);line-height:1.65;color:var(--dsw-alias-label-secondary);overflow-wrap:anywhere;}',
  '.dshWmWikiMore{font-size:var(--wm-text-sm);line-height:1.7;color:var(--dsw-alias-label-secondary);}',
  '.dshWmWikiMore summary{cursor:pointer;font-size:var(--wm-text-xs);color:var(--wm-text-dim);}',
  '.dshWmWikiPlain{margin:.5em 0 0;}',
  '.dshWmWikiExcerpt{margin:8px 0 0;padding-left:10px;border-left:2px solid var(--dsw-alias-border-l2);}',
  '.dshWmWikiExcerptWho{font-size:var(--wm-text-xs);color:var(--wm-text-dim);}',
  '.dshWmWikiExcerpt p{margin:2px 0 0;}',
  '.dshWmWikiTags{display:flex;flex-wrap:wrap;gap:4px;margin-top:8px;}',
  '.dshWmWikiTag{font-size:var(--wm-text-xs);padding:1px 7px;border-radius:999px;background:var(--dsw-alias-bg-layer-2);color:var(--dsw-alias-label-secondary);}',
  '.dshWmWikiPlainList{display:flex;flex-direction:column;gap:4px;}',
  '.dshWmWikiPlainRow{display:flex;gap:8px;font-size:var(--wm-text-sm);line-height:1.7;color:var(--dsw-alias-label-secondary);}',
  '.dshWmWikiPlainKind{flex:none;min-width:32px;font-size:var(--wm-text-xs);color:var(--wm-text-dim);}',
  '.dshWmWikiNote{margin:0;font-size:var(--wm-text-xs);color:var(--wm-text-dim);}',
  '.dshWmWikiStats{display:flex;flex-wrap:wrap;gap:14px;font-size:var(--wm-text-sm);color:var(--dsw-alias-label-secondary);}',
  '.dshWmWikiStats b{font-size:var(--wm-text-md);font-weight:650;color:var(--dsw-alias-label-primary);}',
  '.dshWmWikiBars{display:flex;align-items:flex-end;gap:3px;height:46px;padding:6px 0;border-bottom:1px solid var(--dsw-alias-border-l2);}',
  '.dshWmWikiDayBar{flex:1;min-width:5px;max-width:22px;border-radius:var(--wm-radius-s) var(--wm-radius-s) 0 0;background:var(--dsw-alias-brand-primary);opacity:.5;}',
  '.dshWmWikiDayBar.is-hit{opacity:1;}',
  '.dshWmWikiChapters{margin:0;padding-left:22px;display:flex;flex-direction:column;gap:3px;font-size:var(--wm-text-sm);}',
  '.dshWmWikiChapters li{display:flex;align-items:baseline;gap:8px;min-width:0;}',
  '.dshWmWikiChapterName{border:0;background:none;padding:0;font:inherit;color:var(--dsw-alias-label-primary);cursor:pointer;text-align:left;}',
  '.dshWmWikiChapterName:hover{text-decoration:underline;}',
  '.dshWmWikiChapterChars{flex:none;font-size:var(--wm-text-xs);color:var(--wm-text-dim);}',
  '.dshWmWikiChapterGate{flex:none;font-size:var(--wm-text-xs);padding:0 6px;border-radius:999px;background:var(--dsw-alias-bg-layer-2);}',
  '.dshWmWikiChapterGate.is-pass{color:var(--wm-ok);}',
  '.dshWmWikiChapterGate.is-fail{color:var(--wm-err);}',
  '.dshWmWikiChapterHook{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:var(--wm-text-xs);color:var(--wm-text-dim);}',
  '.dshWmWikiStructure{font-size:var(--wm-text-sm);color:var(--dsw-alias-label-secondary);}',
  '.dshWmWikiStructure summary{cursor:pointer;font-size:var(--wm-text-xs);color:var(--wm-text-dim);}',
  '.dshWmWikiTimeline{margin:0;padding-left:18px;display:flex;flex-direction:column;gap:3px;font-size:var(--wm-text-sm);line-height:1.7;color:var(--dsw-alias-label-secondary);}',
  '.dshWmWikiLedgerFoot{display:flex;flex-wrap:wrap;gap:14px;font-size:var(--wm-text-xs);color:var(--wm-text-dim);}',
  '.dshWmWikiLedgerFoot b{font-weight:var(--wm-weight-medium);color:var(--dsw-alias-label-secondary);}',
  '.dshWmWikiHook{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;}',
  '.dshWmWikiDocGroup{display:flex;flex-direction:column;gap:4px;}',
  '.dshWmWikiSubHead{margin-top:6px;font-size:var(--wm-text-xs);font-weight:var(--wm-weight-bold);letter-spacing:.08em;text-transform:uppercase;color:var(--wm-text-dim);}',
  '.dshWmWikiDoc{border:1px solid var(--dsw-alias-border-l2);border-radius:var(--wm-radius-m);background:var(--dsw-alias-bg-layer-1);}',
  '.dshWmWikiDocHead{display:flex;align-items:center;gap:8px;padding:6px 10px;}',
  '.dshWmWikiDocToggle{flex:1;min-width:0;border:0;background:none;font:inherit;font-size:var(--wm-text-sm);color:var(--dsw-alias-label-primary);cursor:pointer;text-align:left;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;}',
  '.dshWmWikiDocChars{flex:none;font-size:var(--wm-text-xs);color:var(--wm-text-dim);}',
  '.dshWmWikiDocBody{padding:4px 14px 14px;border-top:1px solid var(--dsw-alias-border-l2);}',
  '.dshWmWikiBarNote{flex:none;display:flex;align-items:center;gap:10px;padding:8px 24px;font-size:var(--wm-text-sm);border-bottom:1px solid var(--dsw-alias-border-l2);background:var(--dsw-alias-bg-layer-1);color:var(--dsw-alias-label-secondary);}',
  '.dshWmWikiBarNote.is-error{color:var(--wm-err);}',
  '.dshWmWikiExportPath{flex:1;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-family:ui-monospace,Consolas,monospace;font-size:var(--wm-text-xs);color:var(--wm-text-dim);}',

  /* B3 内联样式收编：原 style={{…}} 字面量 → 具名类（值优先用 B1 令牌）。
     运行时算出的高度/宽度等动态值仍留内联（见对应调用点注释）。 */
  '.dshWmSpacer{flex:1;}',
  /* 搜索框变体：flat=去掉独立摆放时的下外边距；grow=行内撑满；compact=顶栏固定宽；compose=备忘输入框 */
  '.dshWmSearch.is-flat{margin:0;}',
  '.dshWmSearch.is-grow{flex:1;}',
  '.dshWmSearch.is-compact{width:180px;margin:0;}',
  '.dshWmSearch.is-compose{margin:0;flex:1;min-width:0;resize:vertical;max-height:140px;font:inherit;}',
  '.dshWmFolder.is-clickable{cursor:pointer;}',
  /* 外壳侧边栏 footer 的入口钮：外观仍由 .dshWmBtn 负责，这里只负责撑满与文字居中 */
  '.dshWmBtn.dshWmEntryBtn{width:100%;justify-content:center;}',
  /* 状态条检查芯片：状态条里唯一「要作者看一眼」的信息，字号与字重都压过元信息 */
  '.dshWmGateState{font-size:var(--wm-text-md);font-weight:var(--wm-weight-bold);}',
  '.dshWmGateState.is-pass{color:var(--wm-ok);}',
  '.dshWmGateState.is-fail{color:var(--wm-err);}',
  /* 状态条元信息（字数/格式/今日净增）：降权，不与检查摘要抢读 */
  '.dshWmStatusMeta{font-size:var(--wm-text-xs);color:var(--wm-text-dim);}',

  /* 文档库：项目创建表单 / 新建文稿行 / 三视图切换 / 搜索框容器 */
  '.dshWmProjForm{padding:0 10px 10px;display:flex;flex-direction:column;gap:6px;}',
  '.dshWmProjFormActions{display:flex;gap:6px;}',
  '.dshWmNewDocRow{display:flex;gap:6px;padding:0 10px 8px;}',
  /* 视图切换与搜索降权（2026-10-10）：它们是 chrome 不是内容——去边框小灰字 tab、
     透明底细边搜索框，把视觉重量让给项目与章节。 */
  '.dshWmLibViews{padding:var(--wm-space-2);display:flex;gap:2px;}',
  '.dshWmLibViews .dshWmBtn{border-color:transparent;color:var(--wm-text-dim);font-size:var(--wm-text-xs);padding:4px 10px;}',
  '.dshWmLibViews .dshWmBtn:hover{color:var(--dsw-alias-label-primary);border-color:transparent;}',
  '.dshWmLibViews .dshWmBtn[aria-pressed="true"]{color:var(--dsw-alias-label-primary);font-weight:var(--wm-weight-medium);background:var(--dsw-alias-bg-layer-2);border-color:transparent;}',
  '.dshWmSearchWrap{padding:var(--wm-space-2) var(--wm-space-2) 0;}',
  '.dshWmSearchWrap .dshWmSearch{background:transparent;border-color:var(--dsw-alias-border-l3);}',
  '.dshWmSearchWrap .dshWmSearch:focus{border-color:var(--dsw-alias-brand-primary);}',

  /* 备忘：配额行 / 说明行 / 编写区 */
  '.dshWmMemoryNote.is-quota{display:flex;flex-wrap:wrap;gap:6px;align-items:center;}',
  '.dshWmCompanionEmpty.is-inline{padding:8px 10px;text-align:left;line-height:1.5;}',
  '.dshWmAiActions.is-padded{padding:0 10px 6px;}',

  /* 设置页（settings.section 槽位，挂在外壳设置弹层、不在 .dshWmRoot 内；令牌由 :root 的 B1 层提供） */
  '.dshWmSettings{width:100%;max-width:640px;display:flex;flex-direction:column;gap:var(--wm-space-1);color:var(--dsw-alias-label-primary);}',
  '.dshWmSetIntro{font-size:var(--wm-text-sm);color:var(--wm-text-dim);margin-bottom:var(--wm-space-2);}',
  '.dshWmSetRow{display:flex;align-items:center;gap:var(--wm-space-3);padding:var(--wm-space-2) 0;}',
  '.dshWmSetRow.is-top{align-items:flex-start;}',
  '.dshWmLabel{width:120px;flex:none;color:var(--dsw-alias-label-secondary);font-size:var(--wm-text-sm);}',
  '.dshWmSetHint{font-size:var(--wm-text-sm);color:var(--wm-text-dim);line-height:1.5;}',
  '.dshWmField{padding:6px 10px;border-radius:var(--wm-radius-m);border:1px solid var(--dsw-alias-border-l2);background:var(--dsw-alias-bg-layer-2);color:var(--dsw-alias-label-primary);font:inherit;font-size:var(--wm-text-sm);}',
  '.dshWmField.is-grow{flex:1;}',
  '.dshWmField.is-num{width:90px;padding:6px 8px;}',
  '.dshWmSetColumn{flex:1;display:flex;flex-direction:column;gap:6px;}',
  '.dshWmSetRootRow{display:flex;align-items:flex-start;gap:var(--wm-space-2);font-size:var(--wm-text-sm);padding:var(--wm-space-1) 0;border-top:1px solid var(--dsw-alias-border-l3);}',
  '.dshWmSetRootMain{flex:1;min-width:0;display:flex;flex-direction:column;gap:2px;}',
  '.dshWmSetRootTitle{display:flex;align-items:center;gap:6px;flex-wrap:wrap;}',
  '.dshWmSetRootOps{display:flex;align-items:center;gap:6px;flex:none;}',
  '.dshWmTag{font-size:var(--wm-text-xs,11px);line-height:1.6;padding:0 6px;border-radius:999px;border:1px solid var(--dsw-alias-border-l2);color:var(--wm-text-dim);}',
  '.dshWmTag.is-on{color:var(--dsw-alias-brand-primary);border-color:var(--dsw-alias-brand-primary);}',
  '.dshWmTag.is-warn{color:var(--wm-warn);border-color:var(--wm-warn);}',
  '.dshWmSetRootPath{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:var(--wm-text-dim);font-size:var(--wm-text-xs,11px);}',
  '.dshWmSetAddRow{display:flex;gap:var(--wm-space-2);}',
  '.dshWmSetSectionHead{margin-top:var(--wm-space-3);padding-top:var(--wm-space-3);border-top:1px solid var(--dsw-alias-border-l2);font-size:var(--wm-text-sm);font-weight:var(--wm-weight-bold);color:var(--wm-text-dim);letter-spacing:.06em;}',

  /* 选文件夹（2026-10-09）：设置页「浏览…」+ 内置文件夹浏览弹层。
     设置页挂在官方设置弹层里、不在 .dshWmRoot 内，所以遮罩 z-index 必须高过官方弹层。 */
  '.dshWmBrowseBtn{flex:none;white-space:nowrap;}',
  '.dshWmSetHint.is-warn{color:var(--wm-warn);}',
  '.dshWmPickMask{position:fixed;inset:0;z-index:4000;display:flex;align-items:center;justify-content:center;background:rgba(0,0,0,.42);padding:24px;}',
  '.dshWmPickBox{width:min(640px,100%);max-height:min(78vh,720px);display:flex;flex-direction:column;gap:8px;padding:16px;border-radius:var(--wm-radius-l);border:1px solid var(--dsw-alias-border-l2);background:var(--dsw-alias-bg-layer-1);color:var(--dsw-alias-label-primary);box-shadow:0 18px 48px rgba(0,0,0,.32);font-size:var(--wm-text-sm);}',
  '.dshWmPickHead{display:flex;align-items:center;gap:10px;}',
  '.dshWmPickTitle{font-weight:var(--wm-weight-bold);}',
  '.dshWmPickHint{flex:1;min-width:0;font-size:var(--wm-text-xs);color:var(--wm-text-dim);}',
  '.dshWmPickClose{flex:none;font-size:16px;line-height:1;padding:2px 8px;}',
  '.dshWmPickPath{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;padding:6px 10px;border-radius:var(--wm-radius-m);background:var(--dsw-alias-bg-layer-2);border:1px solid var(--dsw-alias-border-l2);font-family:ui-monospace,Consolas,monospace;font-size:var(--wm-text-xs);color:var(--dsw-alias-label-secondary);}',
  '.dshWmPickQuick{display:flex;flex-wrap:wrap;gap:6px;}',
  '.dshWmPickChip{border:1px solid var(--dsw-alias-border-l2);border-radius:999px;background:var(--dsw-alias-bg-layer-2);color:var(--dsw-alias-label-secondary);font:inherit;font-size:var(--wm-text-xs);padding:2px 10px;cursor:pointer;}',
  '.dshWmPickChip:hover{color:var(--dsw-alias-label-primary);border-color:var(--dsw-alias-brand-primary);}',
  '.dshWmPickError{padding:6px 10px;border-radius:var(--wm-radius-m);background:color-mix(in srgb,var(--wm-warn) 12%,transparent);color:var(--wm-warn);font-size:var(--wm-text-xs);}',
  '.dshWmPickList{flex:1;min-height:180px;overflow:auto;display:flex;flex-direction:column;gap:2px;border:1px solid var(--dsw-alias-border-l2);border-radius:var(--wm-radius-m);padding:4px;}',
  '.dshWmPickRow{display:flex;align-items:center;gap:8px;width:100%;text-align:left;border:0;border-radius:var(--wm-radius-s);background:transparent;color:var(--dsw-alias-label-primary);font:inherit;font-size:var(--wm-text-sm);padding:6px 8px;cursor:pointer;}',
  '.dshWmPickRow:hover{background:var(--dsw-alias-interactive-bg-hover,rgba(127,127,127,.12));}',
  '.dshWmPickRow.is-up{color:var(--dsw-alias-label-secondary);}',
  '.dshWmPickRowName{flex:1;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;}',
  '.dshWmPickEmpty{padding:8px 10px;color:var(--wm-text-dim);font-size:var(--wm-text-xs);}',
  '.dshWmPickFoot{display:flex;align-items:center;gap:8px;}',

  /* C2 「＋ 添加资料」下拉：它是选择器不是输入框，用虚线边 + muted 文案区分，
     并允许在窄侧栏里省略号收尾（.dshWmSearch 那套是输入框外观，0,2,0 复合选择器确保压得住它） */
  '.dshWmSearch.dshWmAddRes{max-width:100%;min-width:0;overflow:hidden;white-space:nowrap;text-overflow:ellipsis;border-style:dashed;color:var(--dsw-alias-label-secondary);}',

  /* C3 原生 checkbox 收编品牌色：作用域覆盖工作台根与设置页（设置页在 .dshWmRoot 之外） */
  '.dshWmRoot input[type="checkbox"],.dshWmSettings input[type="checkbox"]{accent-color:var(--dsw-alias-brand-primary,#2b5fd9);}',

  /* C4 文稿名里的版本号降权（textContent 不变）：版本信息的主展示位是下方版本条 chips */
  '.dshWmDocVer{font-size:var(--wm-text-sm);font-weight:var(--wm-weight-normal);color:var(--wm-text-dim);}',

  /* C11 补齐三个「JSX 里有、样式表里没有」的既有类 */
  '.dshWmMemoryStatus{flex:none;color:var(--dsw-alias-label-secondary);}',
  '.dshWmMemoryStatus[data-status="confirmed"]{color:var(--wm-ok);}',
  '.dshWmMemoryStatus[data-status="retracted"]{color:var(--wm-text-dim);}',
  '.dshWmMemoryStatus[data-status="resolved"]{color:var(--dsw-alias-brand-primary);}',
  '.dshWmWikiLedger{display:flex;flex-direction:column;gap:6px;}',
  '.dshWmWorldProjection{display:flex;flex-direction:column;gap:6px;padding:6px 8px;border:1px dashed var(--dsw-alias-border-l2);border-radius:var(--wm-radius-s);background:var(--dsw-alias-bg-layer-2);}',

  /* 产品化动效（2026-10-10 第六轮）：进驻与展开用 120–180ms 浅位移淡入——够感知、不拖节奏；
     prefers-reduced-motion 下全部关停。 */
  '@keyframes dshWmFadeUp{from{opacity:0;transform:translateY(4px)}to{opacity:1;transform:none}}',
  '@keyframes dshWmFadeSide{from{opacity:0;transform:translateX(-8px)}to{opacity:1;transform:none}}',
  '@keyframes dshWmFadeSideR{from{opacity:0;transform:translateX(8px)}to{opacity:1;transform:none}}',
  '.dshWmRoot{animation:dshWmFadeUp .18s ease-out;}',
  '.dshWmSide{animation:dshWmFadeSide .16s ease-out;}',
  '.dshWmSide.is-ai{animation:dshWmFadeSideR .16s ease-out;}',
  '.dshWmProjOps{animation:dshWmFadeUp .12s ease-out;}',
  '.dshWmProj details[open]>.dshWmItem{animation:dshWmFadeUp .12s ease-out;}',
  '@media (prefers-reduced-motion:reduce){',
  '  .dshWmRoot,.dshWmSide,.dshWmSide.is-ai,.dshWmProjOps,.dshWmProj details[open]>.dshWmItem{animation:none !important;}',
  '  .dshWmItem,.dshWmIconBtn{transition:none !important;}',
  '}',
].join('\n')

const TAG = 'dsh-writing-mode-css'

export function ensureWritingCss() {
  if (typeof document !== 'undefined' && !document.getElementById(TAG)) {
    const tag = document.createElement('style')
    tag.id = TAG
    tag.textContent = CSS
    document.head.appendChild(tag)
  }
}
